### ISSUE TITLE
linkTarget option doesn't change behavior

### ISSUE THREAD

**Issue by Digital-jedi12** [totaldebug/atomic-calendar-revive#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on an event title in either cal or event mode opens a new tab instead of the desired URL by declaring:

linkTarget: calendar.google.ca

### Expected behaviour

I'm expecting that by declaring this variable, the links should direct to the google cal website.

### Card Version

7

### Home Assistant Version

2023.4.5

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Family Itinerary
enableModeChange: true
entities:
  - entity: calendar.1
    color: cyan
    name: 1
    linkTarget: https://calendar.google.com/
  - entity: calendar.2
    color: pink
    name: 2
  - entity: calendar.3
    color: yellow
    name: 3
  - entity: calendar.4
    color: green
    name: 4
showColors: true
maxDaysToShow: 10
firstDayOfWeek: 1
refreshInterval: 60
showDate: true
showMultiDayEventParts: false
hideDuplicates: true
showCurrentEventLine: false
showMonth: true
showWeekDay: true
disableEventLink: false
linkTarget: calendar.google.ca
showNoEventsForToday: true
showNoEventDays: true
disableLocationLink: false
showEventIcon: true
showWeekNumber: false
showHiddenText: false
showDatePerEvent: false
showTimeRemaining: false
showEventDate: true
showCalendarName: true
showLastCalendarWeek: false
calShowDescription: false
disableCalEventLink: false
disableCalLink: false
dimFinishedEvents: true
showFullDayProgress: false
sortByStartTime: true
compactMode: false
hoursOnSameLine: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Link target is about how it opens the link e.g. on another tab or in the same tab. 

see docs: https://docs.totaldebug.uk/atomic-calendar-revive/configuration/main.html
