### ISSUE TITLE
Clicking on the title will open existing page in a new tab

### ISSUE THREAD

**Issue by AcornOriginals** [totaldebug/atomic-calendar-revive#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My apologies, this was what i was trying to explain on my last post.

Clicking on the title of an event just reopens the same page again instead of opening Google Calendar.

FYI, The map link works correctly when location data is used.

Interestingly, for days with 'No Events', that text clicks into Google Calendar correctly.

![Capture](https://user-images.githubusercontent.com/96245790/233488938-fc9fd8f9-b007-4f23-a978-5313f1a4eaf2.PNG)

### Expected behaviour

Clicking on the title should open a new window with Google Calendar

### Card Version

7

### Home Assistant Version

2023.4.5

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Family Itinerary
enableModeChange: true
entities:
  - entity: calendar.1
    color: cyan
    name: 1
    linkTarget: https://calendar.google.com/
  - entity: calendar.2
    color: pink
    name: 2
  - entity: calendar.3
    color: yellow
    name: 3
  - entity: calendar.4
    color: green
    name: 4
showColors: true
maxDaysToShow: 10
firstDayOfWeek: 1
refreshInterval: 60
showDate: true
showMultiDayEventParts: false
hideDuplicates: true
showCurrentEventLine: false
showMonth: true
showWeekDay: true
disableEventLink: false
linkTarget: www.google.ca
eventLinktarget: www.google.com
showNoEventsForToday: true
showNoEventDays: true
disableLocationLink: false
showEventIcon: true
showWeekNumber: false
showHiddenText: false
showDatePerEvent: false
showTimeRemaining: false
showEventDate: true
showCalendarName: true
showLastCalendarWeek: false
calShowDescription: false
disableCalEventLink: false
disableCalLink: false
dimFinishedEvents: true
showFullDayProgress: false
sortByStartTime: true
compactMode: false
hoursOnSameLine: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This is due to changes made by home assistant, they removed a lot of features from the calendar API which stopped quite a few things working. This being one, I have requested this be added back but nothing has been done yet.

**Comment by rauwman** [comment]
Hi,
first thx for yaour work.
could you integrate the possiblity to deactivate tap_action or to set give the ability to change the navigation direction?
Regards

**Comment by marksie1988** [comment]
Hi, 
This can be done with  the setting `disableEventLink: true`
