### ISSUE TITLE
BUG: showNoEventsForToday not showing expeected content

### ISSUE THREAD

**Issue by quadcom** [totaldebug/atomic-calendar-revive#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ACR v7.3.0
Home Assistant 2023.5.2 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend 20230503.3 - latest 

The switch for `showNoEventsForToday: true` is listed to display _"No events for today"_ but instead it is showing _" No events"_

![image](https://user-images.githubusercontent.com/7085931/236884529-36b938f9-30f8-411d-abb2-c5549f5766e6.png)

### Expected behaviour

I was expecting the string "No Events For Today"

![image](https://user-images.githubusercontent.com/7085931/236885850-6db27476-75de-4575-af6e-dab4a7598288.png)

Something that would be nice as an alternative fix is a custom string, or even string-array that we could enter in the place of days with no events.

The string array would be fun to have a random string pulled (ie, "nuttn' here dude!", "Sleep in day bro!", "Nada, Zilch Nothing - Game mode on!") that kind of thing. Obviously this is for my son's calendar.

### Card Version

7.30.

### Home Assistant Version

Home Assistant 2023.5.2  Supervisor 2023.04.1  Operating System 10.1  Frontend 20230503.3 - latest 

### Configuration

```shell
type: "custom:atomic-calendar-revive"
name: Today!
refreshInterval: 3600
showNoEventDays: true
showNoEventsForToday: true
showDate: true
disableEventLink: true
disableLocationLink: true
maxDaysToShow: 1
entities:
- entity: calendar.austin_s_schedule
  maxDaysToShow: 1
```

### Relevant log output

```shell
I don't have any logs or don't know where I would find that for this kind of situation.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi there, this is already possible with the option `noEventText`, you can set a custom string. 

The current `no events` text you see is accurate for the default text.

**Comment by quadcom** [comment]
Hey @marksie1988 If that is the case then the bug is in the docs. `noEventText` is not listed as an option.

What is listed is this;
![image](https://user-images.githubusercontent.com/7085931/236913980-14f0a4ca-4399-4ab3-9d22-636e58aa20d5.png)

**Comment by marksie1988** [comment]
https://docs.totaldebug.uk/atomic-calendar-revive/configuration/language.html
