### ISSUE TITLE
Is anyone maintaining this repository?

### ISSUE THREAD

**Issue by bkr1969** [totaldebug/atomic-calendar-revive#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No user assignment for issues with atomic-calendar-revive

### Expected behaviour

Someone should be notified/assigned for issues.  Feedback that they are being fixed would be nice.

### Card Version

Current

### Home Assistant Version

2023.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
yes it is maintained to a point, I have multiple other projects that im working on and i just dont have as muc htime as i would like for this on my own at the moment, you are more than welcome to submit pull requests with features and bug fixes :)
