### ISSUE TITLE
Ability to display the event category

### ISSUE THREAD

**Issue by kleinerhobbit** [totaldebug/atomic-calendar-revive#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no possibility to display the Event-Category.
(at least i have found no way)

### Expected behaviour

I would like to display the event-category which is set on the apointment on the Event-List. 

### Mode

Event (default)

### Context / Reason

I have one shared family calendar on Exchange-Online.
For each member of the houshold there is a category. It would be great when there is an option to display this. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
im not sure this will be possible as this is not a field passed by the HA api. i will confirm

**Comment by marksie1988** [comment]
This is not possible as the HA API doesnt supply that information.

**Comment by kleinerhobbit** [comment]
> This is not possible as the HA API doesnt supply that information.

Hi @marksie1988 
Not sure if im right.
But imo, the relevant calendar information is present in HA Calendar.

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/9987258/d7666ca1-acd6-45c4-8ecc-14868ccd8553)

Would be great when you can take a look at.

**Comment by marksie1988** [comment]
Interesting is that using the caldav integration? Or some other Integration?

**Comment by kleinerhobbit** [comment]
Im using this direct O365 integration, not CalDav.
--> https://github.com/RogerSelwyn/O365-HomeAssistant

**Comment by marksie1988** [comment]
Ok I don't support that, only supported are caldav and Google calendar integration

**Comment by kleinerhobbit** [comment]
Thanks for yout clarification.
Maybe i try to do it by my self.
