### ISSUE TITLE
Time shown in unknown formatting

### ISSUE THREAD

**Issue by JakobTewes** [totaldebug/atomic-calendar-revive#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The meeting time and duration is not shown correctly. Showing up as "strange numbers":

<img width="433" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/22556179/eb33d4fe-3848-48b0-8e15-903aa8a93283">

### Expected behaviour

Show hour and minute correctly :-)

### Mode

Calendar

### Card Version

7.3.0

### Home Assistant Version

2023.6.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This is a configuration issue please supply config as part of the request

**Comment by JakobTewes** [comment]
Hi @marksie1988,

thanks for the reminder and sorry for not providing. This is the config:

´´´
type: custom:atomic-calendar-revive
name: Kalender
enableModeChange: true
defaultMode: Event
entities:
  - entity: calendar.calendar_jt
    name: Jakob
  - entity: calendar.calendar_kl
    name: Katharina
  - entity: calendar.calendar_sl
    name: Sophie
  - entity: calendar.calendar_vl
    name: Viola
eventCalName: true
firstDayOfWeek: 1
maxDaysToShow: 3
showLocation: false
showMonth: true
hoursFormat: 24h
showDate: false
sortByStartTime: false
hideFinishedEvents: true
showRelativeTime: false
showLastCalendarWeek: false
disableCalEventLink: false
showProgressBar: false
refreshInterval: 60
´´´

**Comment by JakobTewes** [comment]
Dammn :-)

<img width="947" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/22556179/6c741f61-a773-4888-b360-c69187446bc8">

**Comment by JakobTewes** [comment]
Another thing is, that I´m running two instances of HA with same configuration. Both show this strange behavior ;-(

**Comment by marksie1988** [comment]
I assume you are running the latest version of HA? 

I am just a little confused, as it you are running a new version like you say above 2023.6.2 the card should pull the time format preference from HA and format the times. 

the other thing to try would be forcing the format by adding this: 

```
hoursFormat: HH:mm
```

this will override the setting in HA

**Comment by marksie1988** [comment]
As there has been no update I'm closing this one

**Comment by JakobTewes** [comment]
Sorry for the late reply. With version 8.0 everything is back to normal - nothing changed, time now showing in correct formatting
