### ISSUE TITLE
Unable to show an icon for a particular calendar

### ISSUE THREAD

**Issue by swampylee** [totaldebug/atomic-calendar-revive#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would ideally like to display an entity_picture next to the title of a calendar event card but in lieu of this option I tried to just use a regular icon. However, whenever I try and set an icon through the UI or via yaml nothing changes. I've use the format mdi:icon but nothing changes. As I said, I'd ideally like to be able to display any graphic using entity_picture customisation but would settle for just being able to display an icon. Maybe I'm doing something wrong........

Awesome card by the way, thanks for all your work on it.

### Expected behaviour

As above

### Mode

Event (default)

### Card Version

7.5.0

### Home Assistant Version

2023.7.2

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar Card
enableModeChange: true
entities:
  - entity: calendar.holidays_in_united_kingdom
    name: Holidays in united kingdom
    icon: mdi:ab-testing
    maxDaysToShow: 30
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Set the option

`showCalendarName: true` 

Only MDI icons are supported.

**Comment by swampylee** [comment]
Hi Steven,

 

I tried that with this code (icon: in either position) and I still don’t get any mdi icons only a generic calendar icon.

 



 

What I’m after is an image to be shown in the title of the card somewhere to identify what the calendar is. So for a list of sporting events the football team’s motif for example.

 

If that’s just not possible I’ll pop in a feature request perhaps.

Thanks for getting back to me.

**Comment by marksie1988** [comment]
> Hi Steven, I tried that with this code (icon: in either position) and I still don’t get any mdi icons only a generic calendar icon. ![image](https://github.com/totaldebug/atomic-calendar-revive/assets/52431327/ec457aef-f0a9-418b-b29b-337faf23b1be) What I’m after is an image to be shown in the title of the card somewhere to identify what the calendar is. So for a list of sporting events the football team’s motif for example. If that’s just not possible I’ll pop in a feature request perhaps. Thanks for getting back to me.

That's not a valid MDI icon, please see this link for all valid icons. https://pictogrammers.com/library/mdi/

**Comment by swampylee** [comment]
> > Hi Steven, I tried that with this code (icon: in either position) and I still don’t get any mdi icons only a generic calendar icon. ![image](https://user-images.githubusercontent.com/52431327/254014176-ec457aef-f0a9-418b-b29b-337faf23b1be.png) What I’m after is an image to be shown in the title of the card somewhere to identify what the calendar is. So for a list of sporting events the football team’s motif for example. If that’s just not possible I’ll pop in a feature request perhaps. Thanks for getting back to me.
> 
> That's not a valid MDI icon, please see this link for all valid icons. https://pictogrammers.com/library/mdi/

It is, it's the first one on their list - I picked that on purpose.

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/52431327/a206b685-fae7-4b3c-80cd-a9a702837cb1)

**Comment by marksie1988** [comment]
Actually yes you are right, I've just tested and mine is also showing the default icon instead of the correct one. I'll have to look into this bug.

**Comment by swampylee** [comment]
> Actually yes you are right, I've just tested and mine is also showing the default icon instead of the correct one. I'll have to look into this bug.

Thanks!

**Comment by marksie1988** [comment]
I have done more testing today and the icons are showing as expected, are you still seeing issues here?

**Comment by swampylee** [comment]
> I have done more testing today and the icons are showing as expected, are you still seeing issues here?

Still appears to be an issue for me.
![IMG_2398](https://github.com/totaldebug/atomic-calendar-revive/assets/52431327/f08a8576-d2c4-4d8b-a9d0-02bf840dc720)

**Comment by marksie1988** [comment]
```
type: custom:atomic-calendar-revive
name: Calendar Card
enableModeChange: true
entities:
  - entity: calendar.holidays_in_united_kingdom
    name: Holidays in united kingdom
    icon: mdi:ab-testing
    maxDaysToShow: 30
showEventIcon: true
```
