### ISSUE TITLE
timed events show as all-day events

### ISSUE THREAD

**Issue by Stooovie** [totaldebug/atomic-calendar-revive#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

all timed events (i.e. events that start at specified time) show as full-day events (showing "24-24" as their time). These are calendars provided by the CalDAV integration, they're iCloud calendars. I have verified the formats and the events seem to be formatted correctly:

```
message: Obby narodeniny 
all_day: false 
start_time: 2023-08-01 14:30:00 
end_time: 2023-08-01 15:30:00 
location:  
description: 
offset_reached: false 
friendly_name: Rodina 
supported_features: 3
```
--

![Screenshot 2023-07-31 at 21 29 24](https://github.com/totaldebug/atomic-calendar-revive/assets/10572373/2c634208-05f4-4a20-926d-366492c851ec)

### Expected behaviour

Events starting at, say, 16:00 show as 16:00.

### Mode

Event (default)

### Card Version

7.5.0

### Home Assistant Version

HA 2023.7.3

### Configuration

```shell
type: custom:atomic-calendar-revive
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 7
refreshInterval: 60
entities:
  - calendar.prace
  - calendar.rodina
  - calendar.domov
  - calendar.spoluprace
calShowDescription: true
showCurrentEventLine: true
showProgressBar: true
showWeekDay: true
showDescription: true
showHiddenText: false
showCalendarName: false
showEventIcon: false
showFullDayProgress: true
hoursFormat: 24
cardHeight: 85
showDate: true
sortByStartTime: true
showRelativeTime: true
hideFinishedEvents: false
hideDuplicates: true
showMultiDayEventParts: true
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLocationLink: false
disableCalLink: false
defaultMode: Event
showDeclined: false
showMultiDay: false
hoursOnSameLine: false
compactMode: false
showMonth: false
disableEventLink: false
showNoEventsForToday: false
showWeekNumber: false
showDatePerEvent: false
showTimeRemaining: false
showEventDate: true
showAllDayHours: false
dimFinishedEvents: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Remove the hoursFormat setting, I think that will fix this.

**Comment by Stooovie** [comment]
Thank you, it did fix the issue. Kinda hidden in the documentation, I wouldn't find it by myself.
