### ISSUE TITLE
Messed up Visual Editor in Home Assistant

### ISSUE THREAD

**Issue by larsschweier** [totaldebug/atomic-calendar-revive#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Visual Editor in Home Assistant ist messed up, i think some Icons or proper formatting are missing.

<img width="293" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/95191737/485f982f-fb42-4309-aa74-93e2abff08c7">

<img width="370" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/95191737/c2346f10-2495-44f9-9e2a-83963074bfb5">

### Expected behaviour

Clean formatting, without texts written on top of each other.

### Mode

Both

### Card Version

7.6.1

### Home Assistant Version

2023.8.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi, Thanks for this, I'm currently working on rewriting the editor I was hoping to have it out already but I have hit some issues that I need to resolve before releasing this.
