### ISSUE TITLE
multi day events - 1st day not showing after update

### ISSUE THREAD

**Issue by guensen0** [totaldebug/atomic-calendar-revive#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

cool calendar at all, but after update to 7.7.1  the multi-day events are do not show the 1st day. 
before, the 1st day was not shown as all-day event but as normal event from 12am to 12pm and the following events were shown as all-day event in calendar mode and in event mode.

Settings:
showMultiDayEventParts: true
showMultiDay: true

When I set showMultiDay: false, the second day is shown, but not the 1st day...

### Expected behaviour

all days from multi-day events shown as all-day events on all days

### Mode

Both

### Card Version

7.7.1

### Home Assistant Version

2023.8.3

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Kalender
enableModeChange: false
entities:
...
showDate: true
showLocation: true
sortByStartTime: true
showAllDayEvents: true
calShowDescription: true
hideFinishedEvents: false
showRelativeTime: true
showMultiDayEventParts: false
showDeclined: false
compactMode: false
offsetHeaderDate: true
defaultMode: Calendar
showLastCalendarWeek: true
disableCalLink: true
disableCalLocationLink: false
disableCalEventLink: false
showMultiDay: false
showFullDayProgress: false
showEventIcon: false
hoursOnSameLine: true
linkTarget: _top
maxDaysToShow: 60
startDaysAhead: 0
view_layout:
  grid-area: header1
card_mod:
  style: >
    table.cal {
      height: 580px !important;
      }
    ha-card {
      background: rgb(17,18,23) !important;
      border-radius: 20px;
      font-size: 18px;
      font-weight: normal;
      border: solid 2px black;
      height: 825px !important;
        }
    .calIcon {
      --mdc-icon-size: 18px !important;
        }
    td.cal {
      vertical-align: top !important;
      }
    ha-card > div.cal-eventContainer > div.calTableContainer > table > tbody >
    td > div > div {
      padding-bottom: 5px !important;
      width: 60px !important;
      }
    .calDay {
      max-width: 60px !important;
      }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guensen0** [comment]
<img width="682" alt="Screenshot 2023-09-14 at 07 42 24" src="https://github.com/totaldebug/atomic-calendar-revive/assets/59560120/cb23f41e-19c5-452e-ad3d-9060986b28ef">
<img width="689" alt="Screenshot 2023-09-14 at 07 43 05" src="https://github.com/totaldebug/atomic-calendar-revive/assets/59560120/28229bf0-56af-4760-9eb6-38adc9880a7d">

**Comment by guensen0** [comment]
cardHeight: 100%
fullDayEventText: All Day
untilText: Until
maxDaysToShow: 6
maxEventCount: 0
showLoader: true
showLocation: false
showMonth: false
showWeekDay: true
fullTextTime: true
showCurrentEventLine: false
showDate: false
dateFormat: LL
startDaysAhead: 0
showLastCalendarWeek: false
sortByStartTime: false
disableEventLink: false
disableLocationLink: false
disableCalMonthLink: false
linkTarget: _blank
hideDeclined: false
showPrivate: true
showHiddenText: false
hiddenEventText: events are hidden
showCalendarName: false
nameColor: var(--primary-text-color)
dateColor: var(--primary-text-color)
dateSize: 90
descColor: var(--primary-text-color)
descSize: 80
showNoEventsForToday: false
noEventText: No events
noEventsForNextDaysText: No events in the next few days
showNoEventDays: false
timeColor: var(--primary-color)
timeSize: 90
showHours: true
showRelativeTime: true
eventTitleColor: var(--primary-text-color)
eventTitleSize: 100
locationIconColor: rgb(--primary-text-color)
locationLinkColor: var(--primary-text-color)
locationTextSize: 90
hideFinishedEvents: false
dimFinishedEvents: true
finishedEventOpacity: 0.6
finishedEventFilter: grayscale(80%)
dayWrapperLineColor: var(--primary-text-color)
eventBarColor: var(--primary-color)
eventCalNameColor: var(--primary-text-color)
eventCalNameSize: 90
showProgressBar: true
showFullDayProgress: false
progressBarColor: var(--primary-color)
progressBarBackgroundColor: '#555'
enableModeChange: true
defaultMode: Event
calGridColor: rgba(86, 86, 86, .35)
calDayColor: var(--primary-text-color)
calWeekDayColor: var(--primary-text-color)
calDateColor: var(--primary-text-color)
defaultCalColor: var(--primary-text-color)
calEventBackgroundColor: rgba(86, 100, 86, .35)
calActiveEventBackgroundColor: rgba(86, 128, 86, .35)
calEventSatColor: rgba(255, 255, 255, .05)
calEventSunColor: rgba(255, 255, 255, .15)
calEventTime: false
firstDayOfWeek: 1
refreshInterval: 60
showEventIcon: true
europeanDate: false
hideDuplicates: false
showMultiDay: true
showMultiDayEventParts: true
showWeekNumber: false
showDescription: false
showEventDate: true
showDatePerEvent: false
showAllDayHours: true
showAllDayEvents: true
offsetHeaderDate: false
titleLength: 0
descLength: 0
type: custom:atomic-calendar-revive
name: Termine
entities:

calShowDescription: false
showDeclined: false
compactMode: false
showTimeRemaining: false
view_layout:
  grid-area: header2
card_mod:
  style: |
    ha-card {
      background: rgb(17,18,23) !important;
      border-radius: 20px;
      font-size: 18px;
      font-weight: normal;
      border: solid 2px black;
      height: 623px !important; overflow-y:scroll!important; 
      }

**Comment by marksie1988** [comment]
This is fixed in the release I'm working on, hopefully ready for release today.

**Comment by guensen0** [comment]
thx
