### ISSUE TITLE
Blocklist does not work with multiple words or phrases

### ISSUE THREAD

**Issue by f0ggy987** [totaldebug/atomic-calendar-revive#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Entering:

`PC,Pay Day`

into the blocklist will not block any events, even when these words appear in the event title.

Additionally the documentation is not clear on formatting required for the blocklist:

- How are multiple words to be specified (comma separated?)
- How are phrases to be specified (single or double quotes?)

### Expected behaviour

Entering:

`PC,Pay Day`

into the blocklist should block events with either **PC** or the phrase **Pay Day** in their title from appearing

Example title - Expected behavior:

**PC session** - should be blocked
**Pay Day** - should be blocked
**Pay the Day Cleaner** - should NOT be blocked

### Steps To Reproduce

Enter a comma separated list of words into the blocklist

### Mode

Event (default)

### Card Version

7.7.1

### Home Assistant Version

2023.9.2

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.family
    name: Family
  - entity: calendar.boston_celtics_calendar_nba
    name: Boston celtics calendar (nba)
  - entity: calendar.[redacted]
    name: Google Calendar
  - entity: calendar.holidays_in_united_states
    name: Holidays in united states
  - entity: calendar.[redacted]
    name: [redacted]
    blocklist: PC,Pay Day
compactMode: false
hoursOnSameLine: false
sortByStartTime: true
showLocation: true
showDate: true
showCurrentEventLine: true
showDescription: false
showFullDayProgress: false
showDatePerEvent: true
showAllDayHours: true
showCalendarName: false
showEventDate: true
showMultiDay: true
showMultiDayEventParts: false
showMonth: false
showEventIcon: false
showTimeRemaining: false
maxDaysToShow: 7
showLoader: false
showRelativeTime: false
offsetHeaderDate: true
showProgressBar: false
showWeekDay: true
showNoEventsForToday: true
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
The description states that it takes regex in the documentation, try this

```
(PC|Pay Day)
```

Or

```
(?:PC|Pay Day)
```

**Comment by f0ggy987** [comment]
Thank you for the quick response! From a quick test it looks like the solution is:

`(PC|Pay Day)`

I thought I had previously tried a RegEx, unsuccessfully but I guess I must have typed it incorrectly :-)

Someone on the forum claimed a comma-separated list worked for them, which sent me down that path.

Thanks again!

**Comment by marksie1988** [comment]
When I first implemented this it was comma separated, but I realised that limited the filter somewhat so moved to regex to allow much more flexibility. 

There may even be scenarios where Commas would work for single word filters
