### ISSUE TITLE
Be very careful to upgrade to version v8.0.0!

### ISSUE THREAD

**Issue by rolfberkenbosch** [totaldebug/atomic-calendar-revive#1151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to version v8.0.0 it stopped working. I got the message: type: custom:atomic-calendar-revive
doesn't exist. I try to remove it and installed the V7.7.2 but this one is also not working any more. Still figuring out what happend with the to upgrade to 8.0.0, it meshed something up in home assistant.

### Expected behaviour

It should show my calendar, like version 7.7.2.

### Steps To Reproduce

I have checked it the javascript is availble in sources and it is. Still looking now in debug logs what happend. Please consider to take this version/upgrade down.

### Mode

Both

### Card Version

8.0.0

### Home Assistant Version

2023.9.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miumer** [comment]
Also getting Custom element doesn't exist after update

**Comment by rolfberkenbosch** [comment]
Found the problem: the hacs upgrade did something wrong with the sources. I changed it to: /hacsfiles/atomic-calendar-revive/null?hacstag=246549747800. 

Also the directory is empty:

```
[root@s01 atomic-calendar-revive]# ls -al
total 12
drwxr-xr-x.  2 root root   49 Sep 15 16:45 .
drwxr-xr-x. 14 root root 4096 Sep 15 16:45 ..
-rw-r--r--.  1 root root  739 Sep 15 16:45 .eslintrc.js
-rw-r--r--.  1 root root  416 Sep 15 16:45 .eslintrc.js.gz
```

The fix is to manually change null to atomic-calendar-revive.js. And download the atomic-calendar-revive.js file from the 7.7.2 release/tag. The release 8.0.0 does not have any .js file on github.

Please review your v8.0.0 release.

**Comment by rolfberkenbosch** [comment]
> Same here, no way to turn back either.

Please look at my solution above.

**Comment by DPKok** [comment]
I've been looking, but were do I even find this?

**Comment by rolfberkenbosch** [comment]
**Here is the fix:**

_Step 1:_
In Home Assistant got to Settings -> Dashboards
Click on the trhee dots above -> Resources
Click on row /hacsfiles/atomic-calendar-revive/null?hacstag=
The the url to: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js?hacstag=246549747800

_Step 2:_
Go to the terminal from home assistant, type the following command:
```bash
cd www/community/atomic-calendar-revive/
```
Press enter, and then type the following command:
```bash
wget https://github.com/totaldebug/atomic-calendar-revive/releases/download/v7.7.2/atomic-calendar-revive.js
```
Press enter

It should now be fixed.

**Comment by pgarciafc** [comment]
I switched to master branch from HACS directly and it worked. No need to go through all the paraphernalia you described above (thanks, though!)

 I get master may not be as stable as getting it from a tag but deffo it goes better than 8.0.0 :-)

**Comment by rolfberkenbosch** [comment]
Thanks @pgarciafc for the quick fix, i will close this one.
