### ISSUE TITLE
All day events are not shown on due date

### ISSUE THREAD

**Issue by criticallimit** [totaldebug/atomic-calendar-revive#1153]
The "all day" attribute in a created sensor.ical_mull_event_0 is shwon as expected "true", even if time is from 0:00 to 0:00

![Bildschirmfoto](https://github.com/tybritten/ical-sensor-homeassistant/assets/5613811/f1991369-19b4-4a52-9f58-17fb7c69c0ee)

But in the calendar sensor.ical_mull it is changing to "false" and not shown in the calendar the day it is due

![Bildschirmfoto 1](https://github.com/tybritten/ical-sensor-homeassistant/assets/5613811/3675cd74-1920-4084-9d00-b7792cf01bdb)

Is this because it is translated automatically by HA? 
In the event sensor it is "all day", but in the calendar sensor it is translated to "ganztägig" and because of this not shown on the day it is due?

### Expected behaviour

all day events from sensor.ical_xxx_event_0 .._1.._2 should be shown when all day-attribute is "true"

### Card Version

8.0.0

### Home Assistant Version

10.5

**Comment by marksie1988** [comment]
You are talking about a sensor? 

This card just displays calendar data and doesnt change any sensors or the way a sensor displays data, for that you would need to speak with the creator of that sensor

**Comment by criticallimit** [comment]
Yes, you are right. It´s a sensors problem which is already solved by update.
