### ISSUE TITLE
Single day event view showing incorrect or incomplete list

### ISSUE THREAD

**Issue by dcode** [totaldebug/atomic-calendar-revive#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A somewhat recent change modified how the event list is populated. This bug is not present in v7.7.1, but it is present in v7.7.2. Seemingly, the days are bucketed according to UTC, but then presented in the user's timezone. I have a dashboard using a grid layout where each grid should show a single day's events. With v8.0.0, any event at 12:01am UTC or later shows up on the following day. I live in the Central Daylight Timezone (UTC-5) and so that means anything after 18:00 (i.e 18:01 or later) will show on the following day. See the screenshot below.

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/171574/f0ccc9f3-2863-4fb5-b74d-0d4ce9ec0c57)

### Expected behaviour

I expected the previous behavior (v7.7.1) where events later in the day would show in the proper grid for that single day.

### Steps To Reproduce

1. Create two cards in Event mode and set `maxDaysToShow` to 1. 
2. On the first card, set `startDaysAhead` to 0.
3. On the second card, set `startDaysAhead` to 1. 
4. Ensure the system (maybe browser?) timezone is not set to UTC.
5. Create one or more calendar events in the time period between the new day in UTC timezone and the system timezone.
6. Observe today's events showing on the next day's card.

### Mode

Event (default)

### Card Version

v8.0.0

### Home Assistant Version

2023.9.3

### Configuration

```shell
# I use `decluttering_templates` to managed multiple instances of
# Atomic Calendar Revive. Here's the template config:
decluttering_templates:
  calendar_dayevent_tpl:
    default:
      grid_area: top-left
      days_ahead: 0
    card:
      type: custom:atomic-calendar-revive
      view_layout:
        grid-area: '[[grid_area]]'
        place-items: start space-evenly
      defaultMode: Event
      enableModeChange: false
      showWeekDay: true
      entities:
        - entity: calendar.one
          name: One
          color: '#51f651'
        - entity: calendar.two
          name: Two
          color: '#f18bf1'
        - entity: calendar.holidays_us
          name: Holidays
      startDaysAhead: '[[days_ahead]]'
      maxDaysToShow: 1
      refreshInterval: 600
      eventTitle: Busy
      hideFinishedEvents: true
      calShowDescription: true
      showMultiDay: true
      showCalendarName: true
      showNoEventDays: true
      showNoEventsForToday: false
      compactMode: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This is related to #1154 I'm currently working on a solution. Closing this in favour of the original issue.
