### ISSUE TITLE
maxDaysToShow still malfunctioning

### ISSUE THREAD

**Issue by variada** [totaldebug/atomic-calendar-revive#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using a dashboard card to show only today's events. worked fine until sometime in September. I know you said it is fixed, but I still get the following behaviour:

with maxDaysToShow: 0 or maxDaysToShow: 1 I get the same list of today's and tomorrow's events (see screenshots) - with higher numbers I always get one more day than expected (either that or maxDaysToShow=0 means "only today")

![Screenshot 2023-10-02 095708](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/a91dcac0-e38c-4ef5-bd61-abad166bada5)
![Screenshot 2023-10-02 095029](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/6f5ebbd5-1af5-4a28-a604-f08f9241500f)
![Screenshot 2023-10-02 095622](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/a797141d-0d98-48ea-8e04-ba95ce6a2dd1)

if I can volunteer more information, please just ask, haven't done many bug reports yet.

and: thanks for the great work at this card! I really love it's versatility.

------------------
afterthought: I just noticed that I can set maxDaysToShow for any given calendar (been using the card for ages, didn't had any cause to change the setup for a long time before the bug). but if I set my three calendars to 1 (days), but don't set any global/card-wide maxDaysToShow than the default kicks in and it shows several days in advance.

### Expected behaviour

only today's events should be shown.

### Steps To Reproduce

- Make a card on any dashboard.
- choose maxDaysToShow: 1
- see today's and tomorrow's events
- change to maxDaysToShow: 0
- see the same

### Mode

Event (default)

### Card Version

9.0.0

### Home Assistant Version

2023.10.b4

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.birthdays
    color: firebrick
    icon: mdi:cake
    maxDaysToShow: 1
  - entity: calendar.cal_5_holidays_in_germany
    color: firebrick
    icon: mdi:calendar-multiselect
    maxDaysToShow: 1
  - entity: calendar.feiertage
    color: firebrick
    icon: mdi:calendar
    maxDaysToShow: 1
name: Today
untilText: until
showHiddenText: false
showDatePerEvent: false
showWeekDay: true
showMonth: true
showProgressBar: true
showCurrentEventLine: false
showFullDayProgress: false
showNoEventsForToday: true
disableLocationLink: true
disableEventLink: true
showEventIcon: true
showCalendarName: false
showWeekNumber: false
hoursOnSameLine: false
showAllDayHours: false
showLastCalendarWeek: false
disableCalLocationLink: true
disableCalEventLink: true
disableCalLink: true
maxDaysToShow: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi, Thanks for using the card i'm glad you like it!

Ok so I think I understand, 

1. when you set `maxDaysToShow: 1` globally it shows 1 days of events, when you set `maxDaysToShow: 0` globally it shows 1 days of events - This is the expected behaviour, the card doesnt allow 0 days to be shown as that would be pointless. 
2. when you set `maxDaysToShow: 1` under a specific entity it is sill showing events for the following day for that entity? - this is a bug, I can look into it. 

Please let me know if I got that right or if i'm missing something.

**Comment by variada** [comment]
yes, and no.

2 is correct. I can screenshot that later for you, if necessary. - but it only happens when there is no entry for global maxDaysToShow. as soon as the global setting is there, it works.

1 when set maxDaysToShow: 1 or 0 it shows today AND tomorrow. always. that's what my screenshots show. (today is a birthday. tomorrow is a public holiday.)

my screenshots explained: 
 pic 1: configuration of the card. (the important bits of it)
 pic 2: card showing today and tomorrow.
 pic 3: the Home Assistant calendar view showing it is two different days.
 
 hope that helps.

**Comment by variada** [comment]
Screenshots for problem No 2:
![Screenshot 2023-10-02 132510](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/7791df2a-c221-456b-be88-4fc9a495c8b8)
pic 1: maxDaysToShow set for all three individual calendars. but no global setting. card shows an event 5 days away.

![Screenshot 2023-10-02 132543](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/e6e8f6cd-83c1-497e-b419-b5ffb618b53e)
pic 2: maxDaysToShow set globally (for the card. circled in red on the screenshot) - card doesn't show the event 5 days away.


--------------
actually the card should show only today's events. but that's problem No 1 as explained above.

**Comment by marksie1988** [comment]
could you confirm do each of these events come from a different calendar? 

Im wondering it its keeping the first day from each calendars events rather than the current day from each calendar, that would make sense with what you are seeing.

**Comment by marksie1988** [comment]
I have released a new beta version, please install and let me know if that has resolved this for you.

**Comment by j0dan** [comment]
I'm having what I'm guessing is a related issue. My maxDaysToShow seems to cut off *early*. I never show till the end of a day. Almost like it's a timezone problem. My timezone is -8. Could OP's be +something?

I've tried beta.2.

**Comment by marksie1988** [comment]
> I'm having what I'm guessing is a related issue. My maxDaysToShow seems to cut off _early_. I never show till the end of a day. Almost like it's a timezone problem. My timezone is -8. Could OP's be +something?
> 
> I've tried beta.2.

Are you using this version: [v9.0.1-beta.1](https://github.com/totaldebug/atomic-calendar-revive/releases/tag/v9.0.1-beta.1)

If so and you still have the issues please could you do the following:

1. when on the atomic calendar card
2. press f12
3. go to console tab
4. expand the entry for atomic calendar revive
5. screenshot the that section, if should include the timezones

P.S. Timezones are the biggest pain in the ....

**Comment by variada** [comment]
still looks wrong to me. it also shows more than one event from one calendar. so it's not only the first event of each.

what happens with 9.0.0.beta1 installed:

Problem 2: if I set maxDaysToShow: 1 only for the calendars, not globally.

card config:
------------
![Screenshot 2023-10-04 125646](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/7b2c48e4-435d-4aa4-be93-3a0c9c807438)
defaultMode: Event
showLoader: false
hideFinishedEvents: true
showRelativeTime: false
showLocation: false
hideDuplicates: false
showProgressBar: false
showMonth: true
showWeekDay: true
disableLocationLink: true
disableEventLink: true
showNoEventsForToday: true
showEventIcon: true
showHiddenText: false
showCalendarName: false
showDatePerEvent: false
showTimeRemaining: false
hoursOnSameLine: true
disableCalLocationLink: true
disableCalLink: true
disableCalEventLink: true
offsetHeaderDate: false
showAllDayEvents: true
allDayBottom: false


------------

card screenshot:
![Screenshot 2023-10-04 125410](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/e34f0ee4-2c4f-4b4b-86ce-daa418774a00)
different colors/icons is different calendars.

**Comment by variada** [comment]
Problem 1:
on the same card as before, if I set maxDaysToShow: 1 globally, I get:

![Screenshot 2023-10-04 125946](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/47793d46-6c20-4193-b012-d2f7b1a964b4)

calendar config as before. card config also the same plus maxDaysToShow:

defaultMode: Event
showLoader: false
hideFinishedEvents: true
showRelativeTime: false
showLocation: false
hideDuplicates: false
showProgressBar: false
showMonth: true
showWeekDay: true
disableLocationLink: true
disableEventLink: true
showNoEventsForToday: true
showEventIcon: true
showHiddenText: false
showCalendarName: false
showDatePerEvent: false
showTimeRemaining: false
hoursOnSameLine: true
disableCalLocationLink: true
disableCalLink: true
disableCalEventLink: true
offsetHeaderDate: false
showAllDayEvents: true
allDayBottom: false
maxDaysToShow: 1

**Comment by variada** [comment]
> 5\. reenshot the that section, if should include the timez

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/83453466/609d4ff0-d7e2-40e2-af4b-b67f934b7938)
that any helpful?

**Comment by marksie1988** [comment]
Hi @variada I think i found the issue with the call to the rest API, please try with the latest beta 9.0.1-beta.2

**Comment by variada** [comment]
Hurray! Problem 1 looks solved.

Problem 2 (no general setting, but individual maxDays settings) still makes Oct 7 show up, though. but that's probably not to worry, because global maxDaysToShow is set to a number by default, right?

**Comment by j0dan** [comment]
The new beta2 solved the issue! Thanks.

**Comment by jbnels** [comment]
Max days to show is not working for me.  I am trying to do a horizontal stack of cards with individual days.  Today works fine, but tomorrow and the next day show two days apiece.
```
type: horizontal-stack
cards:
  - type: custom:atomic-calendar-revive
    name: Today
    entities:
      - entity: calendar.shared
      - entity: calendar.uark
    maxDaysToShow: 1
    startDaysAhead: null
  - type: custom:atomic-calendar-revive
    name: Tomorrow
    entities:
      - entity: calendar.shared
      - entity: calendar.uark
    maxDaysToShow: 1
    startDaysAhead: 1
  - type: custom:atomic-calendar-revive
    name: After
    entities:
      - entity: calendar.shared
      - entity: calendar.uark
    maxDaysToShow: 1
    startDaysAhead: 2
```
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/73153498/926dc5f9-2cbf-4bc8-bb8d-7028f739d362)
