### ISSUE TITLE
Events from previous day are shown "done" on next day; they are not events crossing midnight though

### ISSUE THREAD

**Issue by nicholashead** [totaldebug/atomic-calendar-revive#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have some events that occurred Tuesday night:

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/1168659/7ae00448-8f39-4c52-9c79-8e46b92389ad)

And looking at them on the atomic calendar, they show under Wednesday as completed:

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/1168659/12b64ed2-e5bb-42cb-8970-ede99e73be66)

This is wrong; why would these events show under Wednesday, when they occurred on Tuesday?

### Expected behaviour

I would expect Tuesday events to not be rendered under Wednesday.

### Mode

Event (default)

### Card Version

9.0.0

### Home Assistant Version

2023.9.3

### Configuration

```shell
- type: custom:atomic-calendar-revive
            entities:
              - entity: calendar.holidays_in_united_states
                name: Holidays in US
                color: goldenrod
              - entity: calendar.birthdays
                name: Birthdays
                color: hotpink
              - entity: calendar.my_personal
                name: My personal
                color: mediumslateblue
              - entity: calendar.wife
                name: Wife
                color: orchid
              - entity: calendar.other
                name: Other
                color: palevioletred
            defaultMode: Event
            showWeekDay: true
            showMonth: false
            showProgressBar: true
            showCurrentEventLine: false
            showDescription: false
            disableEventLink: false
            disableLocationLink: false
            showNoEventsForToday: true
            showEventIcon: true
            showFullDayProgress: false
            showWeekNumber: false
            showCalendarName: false
            showDatePerEvent: false
            showTimeRemaining: false
            hoursOnSameLine: false
            calShowDescription: false
            showLastCalendarWeek: false
            showHiddenText: true
            hideFinishedEvents: false
            showLocation: true
            hideDuplicates: true
            showMultiDayEventParts: false
            showMultiDay: false
            compactMode: false
            showAllDayEvents: true
            allDayBottom: false
            offsetHeaderDate: false
            showDate: false
            showRelativeTime: true
            sortBy: start
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi @nicholashead, 

Please upgrade to 9.0.1-beta.2 where this may resolve your issue. 

The latest update resolves an issue with timezones.

**Comment by nicholashead** [comment]
@marksie1988 that did it! Thank you. Verifying this is fixed by https://github.com/totaldebug/atomic-calendar-revive/issues/1191 - specifically https://github.com/totaldebug/atomic-calendar-revive/commit/d92b73dd146d3fa248231808134f701f4b1eca16
