### ISSUE TITLE
Events in calendar not being sorted by startTime

### ISSUE THREAD

**Issue by kaizersoje** [totaldebug/atomic-calendar-revive#1240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed that in my calendar, 2 events for tomorrow are not showing up sorted.

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/54566217/aafc2ae1-d39b-4818-9cb3-c2874a4ca93b)

### Expected behaviour

The events should be sorted by startTyime

### Mode

Event (default)

### Card Version

9.0.2

### Home Assistant Version

2023.10.3

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Home Calendar
entities:
  - entity: calendar.home_calendar
    icon: mdi:home
    color: DARKORANGE
enableModeChange: true
defaultMode: Event
fullDayEventText: All day
untilText: Until
showColors: true
maxDaysToShow: 7
maxEventCount: 6
showLocation: true
showMonth: true
eventTitleColor: BURLYWOOD
locationIconColor: AZURE
locationLinkColor: GAINSBORO
dimFinishedEvents: true
finishedEventOpacity: 0.6
showProgressBar: true
nameColor: DARKKHAKI
calWeekDayColor: '#b8490d'
calDayColor: rgb(179,222,120)
defaultCalColor: '#FF6347'
sortByStartTime: true
showRelativeTime: true
hideFinishedEvents: true
allDayBottom: true
showWeekDay: false
showDescription: false
showCurrentEventLine: false
startDaysAhead: -1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
@kaizersoje are you able to confirm are both these events from the same calendar?

**Comment by kaizersoje** [comment]
Yes they are from the same calendar @marksie1988

**Comment by marksie1988** [comment]
Please check out the latest beta and let me know if that resolves this issue for you.

**Comment by kaizersoje** [comment]
Yes, this has been resolved in the latest beta. Thx.
