### ISSUE TITLE
How to remove the Dot-Icon on no-event-days?

### ISSUE THREAD

**Issue by Maetzi87** [totaldebug/atomic-calendar-revive#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the last update, a big dot-icon is shown on no-event-days
how can I remove it?

### Expected behaviour

I love the Icons for my calendars, but I don't want any icon if theres no event.

### Mode

Event (default)

### Card Version

9.2.0

### Home Assistant Version

2023.10.5

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.1
    icon: mdi:doctor
    color: MediumBlue
  - entity: calendar.2
    color: DarkViolet
    icon: mdi:account-multiple
  - entity: calendar.3
    color: limegreen
    icon: mdi:human-male
  - entity: calendar.4
    color: mediumvioletred
    icon: mdi:party-popper
  - entity: calendar.5
    color: lightseagreen
    icon: mdi:cake-variant
  - entity: calendar.6
    color: firebrick
    icon: mdi:calendar-month
  - entity: calendar.7
    color: HotPink
    icon: mdi:briefcase
maxDaysToShow: 10
maxEventCount: 10
showDate: false
showLoader: true
showNoEventsForToday: true
sortByStartTime: true
showNoEventDays: true
showLocation: false
showWeekDay: true
showMultiDayEventParts: true
showRelativeTime: false
hideFinishedEvents: false
showAllDayEvents: true
hoursOnSameLine: true
weekdayOnSameLine: true
refreshInterval: 120
cardHeight: 534px
fullDayEventText: ganztägig
noEventText: keine Termine
compactMode: false
titleLength: 23
showEventDate: true
showDatePerEvent: false
showEventIcon: true
theme: ios-light-mode-own
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maetzi87** [comment]
Fun fakt: just found out, that the issue appears only on my mobile phone and not on my tablet... therefore I can live with it ;-)

**Comment by Maetzi87** [comment]
Tought it was only on my mobile phone, but after restart it also affects my tablet. Please help!

**Comment by marksie1988** [comment]
ok this does sound like a bug introduced with the latest version, will look at it as soon as i get time :)

**Comment by sevorl** [comment]
The dot is the default icon when a calendar entity does not have an icon.
Set showEventIcon=false to hide the dot.
https://docs.totaldebug.uk/atomic-calendar-revive/configuration/event.html

**Comment by Maetzi87** [comment]
I know that, but I WANT the Icons for my events...
Until the last update, that worked fine

**Comment by Maetzi87** [comment]
Side-question:

Since I use a transparent background for my card, I sourrounded my text with a white outline for better visibility.
For the text, this works fine with card modder using:

`div {  text-shadow: 1px 1px white, -1px -1px white, 1px -1px white, -1px 1px white; }  `

Can anyone tell me, how to get the same outline on the event-icons? I tried several things, but nothing seems to affect the icons...
Just a detail tough, not that important to me ;-)

**Comment by sevorl** [comment]
I set showEventIcon= false and then use emoji as calendar name. The emoji shows at the right instead of the left, but you could probably use some custom css to change the order..

**Comment by Maetzi87** [comment]
Well, I'm still not happy with your solution. Don't want to mess around with css, since I don't have any experience with it. Just want it to work like it did before...

**Comment by marksie1988** [comment]
It's a bug, so it will be fixed. I agree you should have to use CSS to fix this but it's a workaround until I have time to fix it

**Comment by Maetzi87** [comment]
Thank you so much!! 🎉🥳🤗
