### ISSUE TITLE
Only One Event Displayed for Future Days

### ISSUE THREAD

**Issue by VincentClement1** [totaldebug/atomic-calendar-revive#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current day displays All Day Events, Multi-Day and regular Events for multiple calendars. Next day displays two All Day Events and not other events. Future days after next day display only one All Day Event and no other events. 

Previous versions did not exhibit this behaviour. By 'regular" Events, I mean calendar events that are scheduled for a specific time period like meetings. 

This behaviour only appears when you have 2 or more calendars selected. With only one calendar, all events for that calendar are displayed.

### Expected behaviour

Future days should be displaying all events - All Day, Multi Day and regular

### Mode

Event (default)

### Card Version

9.2.0

### Home Assistant Version

2023.10.5

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.axxx
    color: LightSkyBlue
    maxDaysToShow: 14
  - entity: calendar.txxx
    color: Plum
    maxDaysToShow: 14
  - entity: calendar.fxxx
    color: CornFlowerBlue
    maxDaysToShow: 12
  - entity: calendar.jxxx
    color: LightGreen
    maxDaysToShow: 14
  - entity: calendar.cxxx
    color: Tomato
    maxDaysToShow: 14
  - entity: calendar.fxxy
    color: Orange
    maxDaysToShow: 10
calShowDescription: false
cardHeight: 100%
compactMode: false
dateFormat: h:mm a - dddd - D MMMM YYYY
defaultMode: Event
disableCalEventLink: false
disableCalLink: false
disableEventLink: true
disableLocationLink: true
enableModeChange: true
firstDayOfWeek: 1
fullDayEventText: ''
hiddenEventText: Events are hidden
hideDuplicates: true
hideFinishedEvents: true
hoursFormat: h:mm a
hoursOnSameLine: false
maxDaysToShow: 14
maxEventCount: 15
noEventsForNextDaysText: No Events In The Next Few Days
noEventText: No Events Today
refreshInterval: 180
showAllDayHours: false
showCalendarName: false
showCurrentEventLine: false
showDate: true
showDatePerEvent: false
showDescription: false
showEventDate: true
showEventIcon: false
showFullDayProgress: false
showHiddenText: false
showLastCalendarWeek: false
showLoader: false
showLocation: false
showMonth: false
showMultiDay: false
showMultiDayEventParts: false
showNoEventsForToday: false
showProgressBar: false
showRelativeTime: false
showWeekDay: true
showWeekNumber: false
sortBy: start
sortByStartTime: true
startDaysAhead: 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DerRuedi0** [comment]
Exactly the same problem occurred with me, I did not make any changes or anything like that. From one day to the next...

**Comment by VincentClement1** [comment]
Update 2023-10-30: Now showing regular events on other days but seems to be limited to a maximum of four regular events total. After that, only all-day events are displayed. 

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/90101230/01f51070-a170-4fff-bea7-237812a3b3ce)

**Comment by VincentClement1** [comment]
Update 2023-12-11: No regular events are being displayed. Only All-Day events are appearing. Regular events are appearing when I set the card to display one and only one calendar. This is becoming unusable.
