### ISSUE TITLE
"descLength" option does not seem to change description length.

### ISSUE THREAD

**Issue by echo-lalia** [totaldebug/atomic-calendar-revive#1326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting the descLength to an integer value does not appear to make any change to the display of event descriptions. 

`descLength: 10`

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/108598670/3948480b-80db-4b1f-845e-c8eef89e3cdd)

### Expected behaviour

The descriptions should be clipped to the number of characters provided to the descLength value. Or, at least, some change should happen when the value of descLength is changed. 

### Steps To Reproduce

This is all that is needed to reproduce the issue:

```
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.{myEmail}
    name: {myEmail}
showDescription: true
descLength: 10
```

different values for descLength do not result in any different calendar display.

It's worth noting that the visual editor also has an option to set the description length, and the behaviour is the same. 

### Mode

Event (default)

### Card Version

9.2.1

### Home Assistant Version

2023.11.0

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.{myEmail}
    name: {myEmail}
showDescription: true
descLength: 10
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I have just tested this and it is working fine, did you save the configuration or just view it in the preview? sometimes the preview doesnt update until the config is actually saved.

**Comment by echo-lalia** [comment]
Huh, I'm not sure how or why that is.

I was editing the yaml directly, and using a second monitor/window to view the changes, so I don't think that could've been the cause. 

I would've been using Firefox, if there's a chance that's related, but otherwise I don't have a good guess. I'd like to investigate it again to be sure, but I'm a little busy for the next little while, with the holidays.

**Comment by marksie1988** [comment]
Closing this as i dont believe it to be an issue, if there is some more evidence to show it as a bug i will re-open
