### ISSUE TITLE
Some (HA) calendars not showing on mobile devices

### ISSUE THREAD

**Issue by M-See** [totaldebug/atomic-calendar-revive#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Maybe with the current update i encountered the problem, that the internal calendars of HA (not google/outlook ones) are not showing in the card anymore on mobile devices.

### Expected behaviour

Before it worked properly for all kinds of calendars

### Mode

Calendar

### Card Version

9.2.1

### Home Assistant Version

2023.12.3

### Configuration

```
type: custom:atomic-calendar-revive
name: Kalender
enableModeChange: true
entities:
  - calendar.birthdays #from outlook
  - calendar.calendar_test #from outlook
  - calendar.kalender_melus # from outlook
  - calendar.tester # generated within HA --> not shown in mobile version!
  - calendar.https_onlinekalender_ics # from google
  - calendar.hannover_96 # from google
firstDayOfWeek: 1
maxDaysToShow: 60
showDate: false
showMonth: true
showWeekDay: true
showCurrentEventLine: false
showProgressBar: true
showDescription: true
showFullDayProgress: true
showNoEventsForToday: true
showEventIcon: true
max_results: 15
maxEventCount: 15
refreshInterval: 60
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I can't help much without any configuration or information on how you have it setup. 

Please provide this information

**Comment by M-See** [comment]
Hey, i just updated my configuration, but i also saw that now the entries are displayed also on the devices.. i have absolutely no clue why, because i haven´t changed a thing. but now they are shown from the within HA generated-calendars as well.

**Comment by M-See** [comment]
Update.. again it´s not displaying the entries properly anymore. I have never witnessed these strange behaviours before with this integration.

 I defined an appointment on the 22.1.2024 on several calendars (outlook, google, HA-calendar) :

<img width="161" alt="Screenshot 2023-12-22 133938" src="https://github.com/totaldebug/atomic-calendar-revive/assets/60132687/3597daa0-1058-47ac-a3ee-a4a04cfdc8c2">

and none of them is displayed in the view:

<img width="247" alt="Screenshot 2023-12-22 133822" src="https://github.com/totaldebug/atomic-calendar-revive/assets/60132687/5cdf0d9c-6fa1-4669-9733-227eb0330a4c">

the configuration is still the same (and has worked before):

`type: custom:atomic-calendar-revive
name: Kalender
enableModeChange: true
entities:
  - calendar.birthdays
  - calendar.calendar_test
  - calendar.kalender_melus
  - calendar.tester
  - calendar.https_onlinekalender
  - calendar.hannover_96_
firstDayOfWeek: 1
maxDaysToShow: 60
showDate: false
showMonth: true
showWeekDay: true
showCurrentEventLine: false
showProgressBar: true
showDescription: true
showFullDayProgress: true
showNoEventsForToday: true
showEventIcon: true
max_results: 15
maxEventCount: 15
refreshInterval: 60
`

**Comment by M-See** [comment]
> I can't help much without any configuration or information on how you have it setup.
> 
> Please provide this information

The goolge- and outlook calendars do not show up at all (despite the entries being visible in the HA-calendar tab). But based on my configuration, single entries from HA-internal calendars are shown, if there are no other entries on the day. So in the example, i provided, none of the three calendar entries is not displayed, but on another day, where there is no other appointment but from an HA-internal calendar, it´s displayed in the Atomic calendar integration, but it takes very long to update and display it..

To me, it seems very strange, as it has worked smoothly before and should just read out the entries from all the calendars, right?

**Comment by manuelo1983** [comment]
I have the same issue and at one point I found out that it helps for the correct view.
If you activate this option you can see the entries in the calendar.
<img width="343" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/45520344/92df96dc-c067-4d46-a8fe-9ea7631d1176">

**Comment by marksie1988** [comment]
Could you try upgrading to the latest version of the card?

Some big changes to the way events are sorted was implemented. I found incorrect events being removed when using maxEventCount. 

This may resolve that issue.

**Comment by manuelo1983** [comment]
I have updated at the moment but it is strange if I activate this option then i can see all appointments from that day also not whole day appointments. When I deactivate this options only the whole day appointments are in the calendar.

**Comment by M-See** [comment]
> Could you try upgrading to the latest version of the card?
> 
> Some big changes to the way events are sorted was implemented. I found incorrect events being removed when using maxEventCount.
> 
> This may resolve that issue.

I just updated to the newest release and i don´t see any awkward behaviour anymore. So the errors just might have appeared in the previous release. Thank you for your efforts!
