### ISSUE TITLE
Calendar on dashboard causing invalid login on mobile app launch

### ISSUE THREAD

**Issue by squirtbrnr** [totaldebug/atomic-calendar-revive#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a calendar car configured to show about 5 weeks of events from 6 iCal configured calendars. Every day I get an invalid login attempt and the error log shows the requested url is “/api/calendars/calendar.<name_of_calendar>…”. If I remove the calendar card from my dashboard I do not get any invalid login attempts with that api call.

### Expected behaviour

No invalid login should occur.

### Steps To Reproduce

On launch and sometimes refresh of the HA mobile companion app for iOS, an invalid login is logged when a page with the calendar is open.

### Mode

Calendar

### Card Version

v9.2.1

### Home Assistant Version

2023.12.3

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.friends
    name: Friends
  - entity: calendar.b_family
    name: B Family
  - entity: calendar.hockey
    name: Hockey
  - entity: calendar.a
    name: A
  - entity: calendar.appointments
    name: Appointments
  - entity: calendar.o
    name: O
  - entity: calendar.m
    name: M
  - entity: calendar.r_work
    name: R Work
maxDaysToShow: 3
defaultMode: Calendar
showDeclined: false
hideFinishedEvents: false
showDate: true
showLocation: true
hideDuplicates: false
compactMode: false
offsetHeaderDate: false
allDayBottom: false
showWeekDay: false
showCalendarName: true
hoursOnSameLine: false
calShowDescription: false
showLastCalendarWeek: true
disableCalEventLink: false
disableCalLocationLink: false
disableCalLink: false
dimFinishedEvents: true
firstDayOfWeek: 0
dateFormat: LL
```

### Relevant log output

```shell
2023-12-20 10:12:26.137 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from xxxxxxxxxxxxxxxx (###.###.###.###). Requested URL: '/api/calendars/calendar.friends?start=2023-11-26T00:00:00&end=2024-01-06T23:59:59'. (Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 16.7.2) Mobile/HomeAssistant, like Safari)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
hi @squirtbrnr,

Do you have `trusted_proxies` / `trusted_networks` set in your home assistant configuration?

this is not specific to the card and is the home assistant API that is blocking the request due to invalid authentication by a banned IP.

**Comment by squirtbrnr** [comment]
I do not have the trusted proxies or networks option set as I do not use those. I also have the banned IP option disabled. I did have it enabled when this started happening but disabled it and I still get invalid login attempts.

**Comment by marksie1988** [comment]
I'm not sure what would cause this as i dont handle any logins as part of the card, all i do is call the home assistant APIs which gather the required events.

**Comment by squirtbrnr** [comment]
I agree it doesn’t appear to be an issue with the card. I just have never seen this error until I installed and configured this card. And if I remove the card the error stops appearing. However, a recent update of either the HA companion app or HA to 2024.1 seems to have reduced the frequency of these errors and failed logins. No longer happening every day, but maybe every 3-4 days.

**Comment by Bovive** [comment]
I am experiencing this exact problem. Did you ever find a solution? Thanks!
