### ISSUE TITLE
dateFormat option ignores regional format/customization

### ISSUE THREAD

**Issue by squirtbrnr** [totaldebug/atomic-calendar-revive#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The date displayed on the calendar always shows "DD Month YYYY".

### Expected behaviour

With USA region format/customizations set in the frontend, this should display "Month DD YYYY".

### Steps To Reproduce

Set the following option:
`dateFormat: LL`

### Mode

Both

### Card Version

v9.2.1

### Home Assistant Version

2023.12.3

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.friends
    name: Friends
  - entity: calendar.b_family
    name: B Family
  - entity: calendar.hockey
    name: Hockey
  - entity: calendar.a
    name: A
  - entity: calendar.appointments
    name: Appointments
  - entity: calendar.o
    name: O
  - entity: calendar.m
    name: M
  - entity: calendar.r_work
    name: R Work
maxDaysToShow: 3
defaultMode: Calendar
showDeclined: false
hideFinishedEvents: false
showDate: true
showLocation: true
hideDuplicates: false
compactMode: false
offsetHeaderDate: false
allDayBottom: false
showWeekDay: false
showCalendarName: true
hoursOnSameLine: false
calShowDescription: false
showLastCalendarWeek: true
disableCalEventLink: false
disableCalLocationLink: false
disableCalLink: false
dimFinishedEvents: true
firstDayOfWeek: 0
dateFormat: LL
```

### Relevant log output

```shell
None
```
<img width="376" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/35356217/38f3d6d5-a58c-4250-8a61-bedb03a63f2d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Set `dateFromat` to `MMMM D, YYYY` and that will resolve the issue. 

I will review this as currently LL is hard coded as European format.

**Comment by marksie1988** [comment]
Hi All, 

I have just released a new beta, my testing shows this as resolved, please let me know your outcome

**Comment by squirtbrnr** [comment]
I can confirm 9.2.1-beta.2 fixes the `dateFormat: LL` so it follows local/regional format and customizations.

<img width="743" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/35356217/fd1f2bd9-1ac7-4575-9ae2-2d683898fc04">
