### ISSUE TITLE
“The calendar can’t be loaded from Home Assistant component” error every few days, even though the calendar is still linked in HA 

### ISSUE THREAD

**Issue by TomAnks** [totaldebug/atomic-calendar-revive#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Google Calendar named 'Dinner', showing what is for dinner every night.

I installed Atomic Calendar Revive via HACS and added it to my Lovelace dashboard using the following YAML:

```
type: custom:atomic-calendar-revive
name: Meal Plan
enableModeChange: true
entities:
  - entity: calendar.dinner
    name: Dinner
```

The calendar works great for a few days, and then I encounter the following error:

    “The calendar can’t be loaded from Home Assistant component.”

This error is described [in the FAQ](https://docs.totaldebug.uk/atomic-calendar-revive/overview/faq.html#how-to-fix-the-calendar-can-t-be-loaded-from-home-assistant-component), but the calendar is authorised via Home Assistant, as I can see it in 'My Calendars', and it exists as an entity in HA. Plus, the connection works great initially, so the initial connection is clearly working correctly.

The only fix for this is to delete and reauthorise the token via Google Cloud Console, but that is really annoying to have to do every time, and I don't understand why this keeps happening.

Interestingly, if I select another calendar (i.e. my personal Google Calendar), that loads absolutely fine, it is just the 'Dinner' calendar that I am unable to load in Atomic Calendar Revive.

### Expected behaviour

The calendar should not throw the “The calendar can’t be loaded from Home Assistant component.” error after a few days.

### Steps To Reproduce

1. Download Atomic Calendar Revive via HACS
2. Add to Lovelace dashboard
3. Add calendar via Google Calendar integration
4. Wait a few days
5. Calendar unable to be loaded, showing error: “The calendar can’t be loaded from Home Assistant component.”

### Mode

Calendar

### Card Version

9.2.1

### Home Assistant Version

2023.12.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TomAnks** [comment]
![meal plan atomic](https://github.com/totaldebug/atomic-calendar-revive/assets/26800901/635758cb-9382-4a78-a7de-48338a1c96f6)

**Comment by marksie1988** [comment]
Im not sure that this is an issue with the card, you said that other google calendars work fine and it is just this one that has issues? 

The only reason this error would happen is if the card cant get the data it needs from home assistant request.

**Comment by TomAnks** [comment]
Yes, all other calendars seem to work fine, and I can view the 'Dinner' calendar without any issues directly in Home Assistant, so HA is definitely receiving the data, it just disconnects every few days.

**Comment by marksie1988** [comment]
It disconnected from HA every few days? 

Or just on atomic calendar?

**Comment by TomAnks** [comment]
Just Atomic Calendar, it is never disconnected from HA. I tried to check in Google Calendar if there are some different sharing settings selected or something like that, but all the other calendars are set up in the same way.

**Comment by marksie1988** [comment]
Are you still experiencing this issue?

**Comment by TomAnks** [comment]
I haven't tried in a few weeks. I will install the add-on again and let you know in a few days if I still see the same error.

**Comment by TomAnks** [comment]
Thanks @marksie1988! All seems to be working now after 2 weeks, no crashes to report.
