### ISSUE TITLE
Card not working on iOS 12.5.7

### ISSUE THREAD

**Issue by Lofdahl** [totaldebug/atomic-calendar-revive#1343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On my dashboard I get the following error:
"Custom element doesn´t exist: atomic-calendar-revive"
The same dashboard (incl card) loads fine on iPad with iPadOS 17.1.2, iPhone with iOS 17.1.2 both in Safari and Companion App but not on the iPad Air that I use as our "command center"
<img width="519" alt="Dashboard" src="https://github.com/totaldebug/atomic-calendar-revive/assets/81437616/adfc82cf-1685-443e-91b2-246bc79f8b7e">

### Expected behaviour

The card :)

### Steps To Reproduce

Install the card from Hacs on system running iOS 12.5.7 and see if the card loads or not.

### Mode

Both

### Card Version

9.2.1

### Home Assistant Version

2024.1

### Configuration

```shell
- type: custom:atomic-calendar-revive
    entities:
      - entity: calendar.family
        color: white
    dateColor: white
    eventBarColor: red
    timeColor: white
    dayWrapperLineColor: white
    descColor: white
    enableModeChange: true
    firstDayOfWeek: 1
    disableCalLink: false
    showProgressBar: false
    showDescription: false
    showLocation: false
    noEventsForTodayText: Nothing happening today
    dimFinishedEvents: true
    hideFinishedEvents: true
    maxEventCount: 5
    hoursFormat: HH:mm
    dateFormat: YYYY-MM-DD
    refreshInterval: 3600
    showWeekDay: true
    showMonth: false
    showFullDayProgress: false
    showNoEventsForToday: false
    noEventsForNextDaysText: Nothing happening today
    showEventIcon: false
    showHiddenText: false
    calShowDescription: false
    showLastCalendarWeek: false
    showDate: false
    card_mod:
      style: |
        ha-card{
          background: black
        }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This is due to some dependencies the card uses dropping support for older browsers.

**Comment by Lofdahl** [comment]
Thanks for the reply @marksie1988

Okey so these dependencies will not be fixed so that the card can be used in older versions of iOS? I’m not running the dashboard in Safari but in the Companion App (but maybe that is the same)

**Comment by marksie1988** [comment]
The companion app uses the browser in the back, so it's essentially the same. 

It's unlikely as support was removed due to security vulnerabilities and being old

**Comment by Lofdahl** [comment]
Okey, thanks for the explanation. :)

Would it then work if I rolled back the card to a previous version?

**Comment by marksie1988** [comment]
Yes I think v9 or possibly 9.1 should work.

**Comment by steveworkman** [comment]
@marksie1988 could you give me some more detail on which dependency no longer supports iOS 12? I can see that the 9.1 update introduced Lit 3 uses es2021 but the things that it trips up on - optional chaining and nullish coalescing, can be fixed by transpiling some parts of node_modules.
Would you be interested in a PR if I can make this work?

**Comment by marksie1988** [comment]
@steveworkman sure if you can get it working happy for a PR, I just don't have a device that old to test on so can't really do it myself 👍

**Comment by steveworkman** [comment]
As a note, I have it working locally, and I'll try to optimise it over the next few days as the bundle size gets enormous if you try to transpile everything
