### ISSUE TITLE
Error: Custom element doesn't exist

### ISSUE THREAD

**Issue by jtfidje** [totaldebug/atomic-calendar-revive#1349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Gen 1 iPad Air running OS version 12.5.7. This component won't load on the device. It works perfectly fine in the browser on my computer, and after a cache-clear the same issue was fixed on my Android device. However - nothing I've tried have fixed the issue on my iPad

### Expected behaviour

The component loads on the dashboard

### Steps To Reproduce

On an Apple iPad Air Gen. 1 running OS version 12.5.7
Open a dashboard with this component
Behold the error message

### Mode

Event (default)

### Card Version

9.2.1

### Home Assistant Version

2023.12.3

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.tommekalender
    name: Tømmekalender
  - entity: calendar.family
    name: Family
  - entity: calendar.jt
    name: Jahn Thomas
firstDayOfWeek: 1
defaultMode: Event
showDeclined: false
showDate: true
showMultiDay: false
hideDuplicates: true
showAllDayEvents: true
compactMode: false
allDayBottom: true
showWeekNumber: true
showAllDayHours: false
showCalendarName: true
showProgressBar: true
hoursOnSameLine: false
showRelativeTime: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
This was answered in this issue. 

https://github.com/totaldebug/atomic-calendar-revive/issues/1343

**Comment by jtfidje** [comment]
Thank you! I didn't see this - my bad. Sorry for the inconvenience
