### ISSUE TITLE
Home Assistant: Kalender werden seit letztem Update nicht mehr angezeigt

### ISSUE THREAD

**Issue by Uli1900** [totaldebug/atomic-calendar-revive#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Home Assistant: Kalender werden seit letztem Update nicht mehr angezeigt

### Expected behaviour

In Home Assistant geladene Kalender werden angezeigt (wurden bereits angezeigt)

### Mode

Event (default)

### Card Version

 v9.2.1

### Home Assistant Version

Core 2024.1.2

### Configuration

```shell
For example:

type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.apps_by_abfall_4
    icon: ''
  - entity: calendar.feiertage
    name: Feiertage in deutschland
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Please could you confirm if you are using an older device? support for old browsers has been removed from v9.1.0. 

Please share any errors you are seeing to help troubleshoot this.
