### ISSUE TITLE
German language only partly correct

### ISSUE THREAD

**Issue by Nisbo** [totaldebug/atomic-calendar-revive#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My HA is set to German (de) but the displayed language is mixed.
Weekdays are correct but the whole configuration is in english and also the word "Week" is still in english. 
Also setting
```language: de```
in the card configuration and rebooting HA did not solve the problem.
There was an issue with this before, but it was fixed in 2022 and the guy was also able to use ```language: de```

![grafik](https://github.com/totaldebug/atomic-calendar-revive/assets/26260572/41e240c3-e66e-44b9-aa9a-3468efcf33f1)

![grafik](https://github.com/totaldebug/atomic-calendar-revive/assets/26260572/936875bb-dd3a-4e54-895c-c47cbac24d16)

vvv

### Expected behaviour

Configuration in German 
Word "Woche" instead of "Week"

### Mode

Event (default)

### Card Version

v9.2.1

### Home Assistant Version

2024.1

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Schichtplan
enableModeChange: true
entities:
  - entity: calendar.schichtplan_2
    name: Schichtplan
maxDaysToShow: 14
showLastCalendarWeek: false
calShowDescription: false
showDeclined: false
showDate: true
untilText: bis
showWeekDay: true
showMonth: false
disableEventLink: false
showDescription: false
showEventIcon: false
showEventDate: true
showWeekNumber: true
hoursOnSameLine: false
showTimeRemaining: false
showDatePerEvent: false
showCurrentEventLine: false
showMultiDayEventParts: false
showMultiDay: false
disableCalEventLink: false
language: de
dimFinishedEvents: true
cardHeight: 80%
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Im not sure why thats not working for you, I checked and for me it works:

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/adad3871-d6d9-402c-b8df-b20101247070)

could you show me what it shows under the console (press f12 and expand the "atomic-calendar-revive" entry

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/544ea250-cf5b-4079-aba7-84030eb2f5d3)

**Comment by Nisbo** [comment]
![grafik](https://github.com/totaldebug/atomic-calendar-revive/assets/26260572/cb0c2e1e-e573-496a-9575-5d61da69b15f)

**Comment by marksie1988** [comment]
The only other thing i can think is possibly a browser difference.

What browser do you use that i could maybe check with?

**Comment by Nisbo** [comment]
Firefox 121.0.1 (64-Bit)
And also the IOS App

**Comment by dmm1** [comment]
Hi, same here, i have no translation:
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/343625/4c75959d-a1c3-43e4-925e-6ffccc674e23)
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/343625/a69f55bb-cb8e-431d-84eb-3dd0d40b4bbc)
Chrome (latest), Android App

**Comment by MrJeromeV** [comment]
Same problem here for French translation.
Configuration panel is also not translated .

**Comment by marksie1988** [comment]
Thank you guys, I think I have found a bug in the way translations are done. I'm currently trying to figure out how to get around it.

**Comment by marksie1988** [comment]
I have made a fix that I'm doing some final testing on, hopefully have it released to beta tomorrow

**Comment by Nisbo** [comment]
Its working. Good Job :)

**Comment by marksie1988** [comment]
Great glad that has fixed the issue, I will release now.

**Comment by MrJeromeV** [comment]
It’s working fine in 9.3.0-beta.4 but broken again in 9.3.0

**Comment by Nisbo** [comment]
Same for me. Was working in BETA4 but not in 9.3.0
Maybe we need a 9.3.1

**Comment by marksie1988** [comment]
I'm not sure what happened but the beta is still the latest version. For some reason the full release isn't working, I will look into this.
