### ISSUE TITLE
Atomic Calendar Revive within a fixed height layout card doesn't stay the correct size

### ISSUE THREAD

**Issue by efaden** [totaldebug/atomic-calendar-revive#1420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For sake of this bug I made a simple layout-card based grid with a clock-weather-card at the top (min-content) and then an atomic calendar revive at the bottom (1fr) with the height of the layout set to calc(100vh - 60).  The atomic calendar scrolls off of the bottom of the screen when its height is set to 100%,

### Expected behaviour

it should only fill the layout-card.

### Steps To Reproduce

```
  - title: Overview
    path: overview
    type: custom:layout-card
    layout_type: grid
    layout:
      grid-template-columns: auto
      grid-template-rows: min-content 1fr
      height: calc(100vh - 60px)
      margin: 0px 0px 0px 0px !important
      card_margin: 0px 0px 0px 0px !important
      padding: 0px 0px 0px 0px !important
    cards:
      - type: custom:clock-weather-card
        entity: weather.accuweather_accuweather
        title: Home
        sun_entity: sun.sun
      - type: "custom:atomic-calendar-revive"
        card_mod:
          style: |
            .cal-card {
              height: 1fr !important;
              overflow: hidden !important;
            }
        entities:
          - entity: calendar.test
            name: "test"
            ...
            ...
```

### Mode

Event (default)

### Card Version

9.6.1

### Home Assistant Version

2024.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I don't think this is a bug? The card operates the same as other cards. 

if you swap them round the same thing happens, but with the weather card.
