### ISSUE TITLE
Error translating key "ui.common.week" in language when language file doesn't exist

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#1422]
### Discussed in https://github.com/totaldebug/atomic-calendar-revive/discussions/1421

<div type='discussions-op-text'>

<sup>Originally posted by **modo1302** February  9, 2024</sup>
Hey, while in browser's console i get lots and lots of errors. Is this normal?
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/133964285/9ad9cb39-cc30-4b01-a05a-3e858a4f5e6a)
</div>

**Comment by marksie1988** [comment]
Hi, this looks to be a bug when there is no language translation, it should just default to English without this many errors. 

I have raised this issue to look at it.

**Comment by samuele2723** [comment]
Yello, i have same issue
![Screenshot 2024-02-10 alle 19 45 48](https://github.com/totaldebug/atomic-calendar-revive/assets/66970905/057bf840-0568-4de2-8730-18123cca7a3d)
