### ISSUE TITLE
Add Dutch locale (nl)

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#1444]
### Discussed in https://github.com/totaldebug/atomic-calendar-revive/discussions/1403

<div type='discussions-op-text'>

<sup>Originally posted by **rononline** January 29, 2024</sup>
Hello,

can you add the dutch translation??

</div>

**Comment by CaseyRo** [comment]
asjeblieft? https://github.com/totaldebug/atomic-calendar-revive/pull/1446
