### ISSUE TITLE
Events view shows week numbers on the wrong day

### ISSUE THREAD

**Issue by DrJackieBright** [totaldebug/atomic-calendar-revive#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The week number shows between Sunday and Monday
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/98287513/e59c6961-08c8-46fd-b353-af5ba54f12c2)

### Expected behaviour

The week number should show before your set first day of the week. Friday in this case
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/98287513/058007c0-386d-440c-865d-9a2f2f6f40b9)

### Steps To Reproduce

1. Set up the card
2. Set to event mode
3. Set "First day of the week" to a number other than zero

### Mode

Event (default)

### Card Version

9.6.2

### Home Assistant Version

2023.12.3

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.holidays_in_united_states
    name: Holidays in united states
  - entity: calendar.family
    name: Family
  - entity: calendar.ical_work
    name: Work
    icon: [redacted]
    color: red
  - entity: calendar.birthdays
    name: Birthdays
  - entity: calendar.[redacted]
    name: [redacted]
showDate: true
showLocation: false
hideFinishedEvents: false
hideDuplicates: true
showCurrentEventLine: true
showMonth: true
showWeekDay: true
showDescription: true
showNoEventsForToday: true
showFullDayProgress: true
showCalendarName: false
showWeekNumber: true
showDatePerEvent: false
showAllDayHours: true
hoursOnSameLine: false
dimFinishedEvents: true
showEventDate: true
showProgressBar: true
showMultiDayEventParts: false
showMultiDay: false
defaultMode: Event
showEventIcon: true
startDaysAhead: -1
compactMode: false
offsetHeaderDate: false
showNoEventDays: true
maxDaysToShow: 21
cardHeight: 100%
showTimeRemaining: true
untilText: '-'
firstDayOfWeek: 5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Week numbers follow the ISO8601 format, they are done by date not weekdays and it runs Monday to Sunday.
