### ISSUE TITLE
All-day Google Calendar events show times unnecessarily

### ISSUE THREAD

**Issue by melwinek** [totaldebug/atomic-calendar-revive#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All-day Google Calendar events show times unnecessarily

### Expected behaviour

Hours not show.
![Screenshot_20240420-103355_Home Assistant](https://github.com/totaldebug/atomic-calendar-revive/assets/10649327/efef224c-f460-4eb3-a1fe-bb471c3f6768)

### Mode

Event (default)

### Card Version

Newest

### Home Assistant Version

Newest

### Configuration

type: custom:atomic-calendar-revive
name: null
enableModeChange: true
entities:
  - entity: calendar.ical_wspolny
    color: red
    maxDaysToShow: 30
maxDaysToShow: 730
defaultMode: Event
showAllDayHours: false
dimFinishedEvents: true
showLastCalendarWeek: false
calShowDescription: false
showDeclined: true
showDate: true
showProgressBar: true
showWeekDay: true
showMonth: true
showDescription: false
showNoEventsForToday: false
showFullDayProgress: false
showEventDate: true
showLoader: false
showRelativeTime: true
compactMode: false
showAllDayEvents: true
offsetHeaderDate: false
disableCalLocationLink: true
disableCalEventLink: true
disableCalLink: true
disableEventLink: true
disableLocationLink: true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Are you sure they are checked as all day in Google?

**Comment by melwinek** [comment]
Sorry. it's fine now.  This was an ical integration problem.  Using native Google integration it works fine.
