### ISSUE TITLE
Turkish locale\language 

### ISSUE THREAD

**Issue by hknkbp** [totaldebug/atomic-calendar-revive#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please add Turkish locale\language

### Expected behaviour

var o={name:"tr",weekdays:"Pazar_Pazartesi_Salı_Çarşamba_Perşembe_Cuma_Cumartesi".split("_"),weekdaysShort:"Paz._Pzt._Sal._Çar._Per._Cum._Cmt.".split("_"),weekdaysMin:"Paz_Pzt_Sal_Çar_Per_Cum_Cmt".split("_"),months:"Ocak_Şubat_Mart_Nisan_Mayıs_Hazıran_Temmuz_Ağustos_Eylül_Ekim_Kasım_Aralık".split("_"),monthsShort:"Oca._Şub._Mar._Nis._May._Haz._Tem._Ağu._Eyl._Eki._Kas._Ara.".split("_"),ordinal:function(e){return e+"."},weekStart:1,formats:{LT:"HH:mm",LTS:"HH:mm:ss",L:"DD.MM.YYYY",LL:"D. MMMM YYYY",LLL:"D. MMMM YYYY HH:mm",LLLL:"dddd, D. MMMM YYYY HH:mm"},relativeTime:{future:"in %s",past:"vor %s",s:a,m:a,mm:a,h:a,hh:a,d:a,dd:a,M:a,MM:a,y:a,yy:a}};return i.default.locale(o,null,!0),o}(c())}({exports:{}});!function(e,t){e.exports=function(e){function t(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var i=t(e),n={s:"birkaç saniye",m:["bir dakika","bir dakika"],mm:"%d dakika",h:["bir saat","bir saat"],hh:"%d saat",d:["bir gün","bir gün"],dd:["%d gün","%d günler"],M:["bir ay","bir ay"],MM:["%d ay","%d ay"],y:["bir sene","bir yıl"],yy:["%d sene","%d yıl"]};function a(e,t,i){var a=n[i];return Array.isArray(a)&&(a=a[t?0:1]),a.replace("%d",e)}

### Steps To Reproduce

I translated German locale. Please ask if more is needed, would love to contribute.

### Mode

Both

### Card Version

v9.7.0

### Home Assistant Version

Core 2024.5.5 Supervisor 2024.05.1 Operating System 12.3 Frontend 20240501.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
this is not a bug, please raise a discussion feature request with the relevant translations
