### ISSUE TITLE
Not working in Fully Kiosk Browser

### ISSUE THREAD

**Issue by DaveTiff** [totaldebug/atomic-calendar-revive#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On my Desktop PC (Chrome) & HA App (Android) but on my Android tablet I get an error message "Custom element doesn't exist: atomic-calendar-revive"

This worked ok on V9.02

### Expected behaviour

The same as my PC

### Steps To Reproduce

Upgrade from any version after 9.0.2

### Mode

Event (default)

### Card Version

9.7

### Home Assistant Version

2024.6.4

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - entity: calendar.xxxxxxxx_hotmail_co_uk
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 3
refreshInterval: 60
showDate: false
dimFinishedEvents: true
calShowDescription: false
showLastCalendarWeek: false
showCurrentEventLine: false
showMonth: true
showDescription: false
showWeekDay: true
showNoEventsForToday: true
showEventIcon: false
showFullDayProgress: false
disableLocationLink: false
showLocation: false
sortByStartTime: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Please try with 9.8.0-beta.3

**Comment by DaveTiff** [comment]
Ok but Before In do how can I downgrade to 9.0.2, does not appear in HA options?

**Comment by marksie1988** [comment]
If you remove it and then reinstall it you can select a specific version

**Comment by Mincka** [comment]
I have the same error in Firefox for all the beta versions of 9.8.
Downgrading to 9.7 works fine.

**Comment by marksie1988** [comment]
I'm not sure how that would happen, the only difference between 9.7 and 9.8 beta 1/2 is adding the Spanish locale which wouldn't cause this error. 

9.8 beta 3 adds extra compatibility for older devices hence why it's more likely to work with an older device. So if 9.7 works there's no reason 9.8 shouldn't work.
