### ISSUE TITLE
Language setting (nl) not working after save

### ISSUE THREAD

**Issue by benjamin-dcs** [totaldebug/atomic-calendar-revive#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `language: nl` setting does not persist after save, see screenshots

### In edit:
![image](https://github.com/user-attachments/assets/0de109dc-051d-4d04-89f6-d94fceb3d7e4)

### In dashboard:
![image](https://github.com/user-attachments/assets/99c7f64f-4a79-40c3-a8d6-ae6cb40d17fa)

### Expected behaviour

The `language: nl` setting persists after save

### Mode

Calendar

### Card Version

v10.0.1-beta-1

### Home Assistant Version

2024.8.1

### Configuration

```shell
type: vertical-stack
cards:
  - type: custom:button-card
    template: header_button
    label: agenda
  - type: custom:atomic-calendar-revive
    entities:
      - entity: calendar.prive
    card_mod:
      style: |
        .single-event-container {
          grid-template-columns: 0.6fr 2fr !important;
        }
    defaultMode: Event
    language: nl
    hoursOnSameLine: true
    showRelativeTime: false
    showWeekNumber: true
    maxDaysToShow: 14
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
You shouldn't need the language option, the card uses the language set in home assistant. 

Could you press f12 and find any errors related to the card in the console, this will help understand why it's not working as expected.

**Comment by benjamin-dcs** [comment]
My system/HA is in english, but wish to use the card in Dutch. I accidentally actually solved it. I have two cards on one dashboard, thought I had copied the one to the other, but the 2nd didn't have the language setting. By adding the language parameter to the second card, they are now both in Dutch. Guess it's good to know you can't have two languages on one page 😋
