### ISSUE TITLE
Random error: 'Custom element doesn't exist' appears/disappears on refresh 

### ISSUE THREAD

**Issue by Zwoet** [totaldebug/atomic-calendar-revive#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the latest Hassio update to 13.1 I frequently all my calendars show up with the error 'Custom element doesn't exist:atomic-calendar-revive.' 

When my dashboard does a refresh it's okay again. This happens pretty often during the day. 
Everything is updates to the latest version, I tries upgrading from atomic v10.0.0 to v10.0.1-bèta 1 pre-release, but unfortunately it still happens.

Does anyone had the same and manage to fix this ?

### Expected behaviour

Work all the time.

### Mode

Calendar

### Card Version

V10.0.0

### Home Assistant Version

13.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Is this issue still appearing?

**Comment by Zwoet** [comment]
After an update from HA the issue was gone, it was during the auto refresh where sometimes the error appeared and then it would work again the next auto refresh. The only card that seemed effected on my dashboard was Atomic Calendar.
