### ISSUE TITLE
Show multi day events on all days

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#320]
## Summary

It would be nice to have that event shown on all days with the information which day of the total duration it is. E.g. "Eventname (2/5)"

## Additional context

The first one starts today at 10 ends in three days. This one is shown in the calendar only today but tells that it ends in three days. So that part is more like a feature request: It would be nice to have that event shown on all days with the information which day of the total duration it is. E.g. "Eventname (2/5)"

**Comment by alnavasa** [comment]
Is this solved? I have just added my first multi day event, and it just shows the first day.
