### ISSUE TITLE
Subsequent recurring event show up as past event 

### ISSUE THREAD

**Issue by Ullas-Aithal** [totaldebug/atomic-calendar-revive#412]
I'm having this issue where recurring events show up as past event. For example, If I create a recurring event for tomorrow, it shows up as an event with 1 day remaining but the same event next moth shows up before 15 days (as per my config) but it shows up as past event. I think it's because of start date is in the past? I'm using radicale as my caldav provider. 

## Expected behaviour

Recurring event should show up as future event
## Current behaviour

Recurring event is showing up as past event
## Screenshot

Showing up as past event:
![image](https://user-images.githubusercontent.com/10265443/109829171-49669c00-7c63-11eb-8f76-7b93afea9fa7.png)

Recurring event of this month details:
![image](https://user-images.githubusercontent.com/10265443/109829413-816ddf00-7c63-11eb-81c0-52d371efa292.png)

Recurring event series details:
![image](https://user-images.githubusercontent.com/10265443/109829526-9fd3da80-7c63-11eb-9240-f264ffc3ab56.png)

## Possible reasons and solutions

Maybe the end date of the recurring series is considered instead of current recurring event's end date?

## Steps to reproduce

1. Create a recurring event every month starting tomorrow
2. The event shows up with 1 day remaining for this month
3. Next month it shows up 1 day before (depending on the config) but it shows up as past event

## Context

Currently, with this behavior, the actual date of the event doesn't show on the calendar.

## Your environment

Version: 3.2.1
My config:

```
type: 'custom:atomic-calendar-revive'
enableModeChange: true
entities:
  - entity: calendar.shared
showCurrentEventLine: false
showWeekDay: false
showMonth: true
showDescription: false
showEventIcon: false
dimFinishedEvents: true
firstDayOfWeek: 1
maxDaysToShow: 15
sortByStartTime: false
showRelativeTime: true
showProgressBar: false
showNoEventsForToday: false
showFullDayProgress: true
showLoader: false

```
## Checklist

- [X] I searched the current issues and the issue is not known.
- [X] I searched the troubleshooting and there's no fix available for this bug.
- [X] I searched on Google, YouTube, Reddit and there's no fix.
- [X] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
I have done a quick test with this and can see that this is related only to CalDav calendars. 

When doing the same with a Google Calendar the recurrence is shown as normal. 

I will begin troubleshooting on this issues shortly to see what information CalDav supplies for recurring tasks and compare that to Google Calendar.

**Comment by marksie1988** [comment]
Looks like this  is an issue with the way caldav works with HA, not sure that I will be able to resolve this without the HA team modifying the integration. 

I will look at logging something with them.

**Comment by bkr1969** [comment]
They seem to have closed the issue but it does not seem to be resolved.

**Comment by marksie1988** [comment]
As stated this has now been resolved, closing.
