### ISSUE TITLE
All Day Events also on the day after

### ISSUE THREAD

**Issue by bchilton9** [totaldebug/atomic-calendar-revive#416]
My All day events show on the day of the event and the next day in the month view.

[https://ibb.co/LZD2JDX](url)

Its correct in the events. yesterday was grandmas Birthday.
In the month view theres another purple dot on the 12th that says grandmas birthday as well.
Thank you for any help

**Comment by marksie1988** [comment]
hey @bchilton9 

Could you confirm what type of calendar you are using? is it caldav or google?

**Comment by nathanmfast** [comment]
I'm having a very similar issue. I have my primary google calendar, as well as an Outlook Office365 calendar that I have as a shared calendar in google calendar. If its monday and I'm viewing 1 day only for a summary of today's events, and on tuesday there is an all day event on both of my calendars, the one the google calendar that was the results of sharing from Outlook Office365 will show up on today's events, but the regular google calendar one will not.

**Comment by nathanmfast** [comment]
My suspicion is that this has something to do with the timezone difference between the two calendars. Since the calendar that is behaving correctly is on my normal timezone and the one that is behaving oddly is on UTC.

**Comment by marksie1988** [comment]
@nathanmfast is the calendar that is acting oddly connected via CalDav?

**Comment by fangface** [comment]
I am seeing this as well with a caldav calendar.

**Comment by marksie1988** [comment]
Thanks, I will look into this shortly.

**Comment by fangface** [comment]
https://github.com/home-assistant/core/issues/25814

**Comment by ftorkler** [comment]
[home-assistant/core#25814](https://github.com/home-assistant/core/issues/25814) is fixed by [home-assistant/core#48642](https://github.com/home-assistant/core/pull/48642) since June 2021.
So the label `state/blocked` can be removed for this issue here.
