### ISSUE TITLE
Add Hungarian language

### ISSUE THREAD

**Issue by tanker11** [totaldebug/atomic-calendar-revive#473]
Hello,

May I request Hungarian language to be added?
I do like the calendar, and would like to use for my family members, and not all undertand English well.

Thanks in advance

**Comment by marksie1988** [comment]
Thanks for using the card,

I will be doing some work on the card today so should be able to add this in the next release.

**Comment by tanker11** [comment]
Thanks a lot, works correctly!

**Comment by forreggbor** [comment]
Hello. Hungarian langauge is not working in v9.0.2 even it was already added in 2021. 
Could it be possible to add this language again?
Or even better to add a separate language file so anybody can translate it.
Thank you

**Comment by marksie1988** [comment]
Hi @forreggbor, 

Thanks for raising this, it seems hungarian was not properly added previously! I'm not sure why but I didn't add the translation file, if you are able could you translate the below for me? Once I have this I can implement it. 

```
{
	"common": {
		"version": "Version",
		"show_warning": "Show Warning",
		"error": "Error",
		"description": "An advanced calendar card for Home Assistant with Lovelace.",
		"fullDayEventText": "All Day",
		"untilText": "Until",
		"noEventText": "No events",
		"noEventsForNextDaysText": "No events in the next few days",
		"hiddenEventText": "events are hidden"
	},
	"ui": {
		"common": {
			"previous": "Previous",
			"next": "Next",
			"week": "Week"
		}
	},
	"errors": {
		"invalid_configuration": "Invalid Configuration",
		"update_card": "The calendar can't be loaded from Home Assistant component",
		"no_entities": "You have not specified any entities"
	},
	"required": {
		"name": "Required",
		"secondary": "Required options for this card to function"
	},
	"main": {
		"name": "Main Options",
		"secondary": "Options that apply globally",
		"fields": {
			"name": "Name",
			"showColors": "Show Colors",
			"maxDaysToShow": "Max days to show",
			"showLocation": "Show location icon",
			"showLoader": "Show loader animation",
			"showDate": "Show date on card",
			"showDeclined": "Show declined events",
			"sortBy": "Sort by",
			"allDayBottom": "Show all day events at the bottom",
			"hideFinishedEvents": "Hide finished events",
			"dateFormat": "Date format",
			"hoursFormat": "Hours format",
			"defaultMode": "Default mode",
			"linkTarget": "Link target",
			"refreshInterval": "Refresh Interval",
			"showRelativeTime": "Show Relative Time",
			"firstDayOfWeek": "First Day of Week 0-6",
			"cardHeight": "Card Height",
			"hideDuplicates": "Hide duplicates",
			"showMultiDay": "Split Multi-Day Events",
			"showMultiDayEventParts": "Show Multi-Day Event Parts",
			"eventTitle": "Set blank event title",
			"compactMode": "Enable compact mode",
			"titleLength": "Max title length (0 for unlimited)",
			"descLength": "Max description length (0 for unlimited)",
			"showAllDayEvents": "Show all day events",
			"offsetHeaderDate": "Offset header date",
			"startDaysAhead": "Events starting `x` days from today"
		}
	},
	"event": {
		"name": "Event Mode",
		"secondary": "Event Mode specific options",
		"fields": {
			"showCurrentEventLine": "Show line before event?",
			"showProgressBar": "Show progress bar?",
			"showMonth": "Show month?",
			"showWeekDay": "Show Week Day",
			"showDescription": "Show Description?",
			"disableEventLink": "Disable links in event title?",
			"disableLocationLink": "Disable links to location?",
			"showNoEventsForToday": "Show No Events Today?",
			"showFullDayProgress": "Show full day event progress?",
			"untilText": "until text:",
			"noEventText": "No events today text:",
			"noEventsForNextDaysText": "No events in the next few days text:",
			"fullDayEventText": "Full day event text:",
			"showEventIcon": "Show Event Icon",
			"showHiddenText": "Show hidden event text?",
			"hiddenEventText": "Text for hidden events:",
			"showCalendarName": "Show calendar name",
			"showWeekNumber": "Show week numbers",
			"showEventDate": "Show date for events",
			"showDatePerEvent": "Show date next to each event",
			"showTimeRemaining": "Show time remaining",
			"showAllDayHours": "Show All Day event text",
			"hoursOnSameLine": "Show hours on the event line"
		}
	},
	"calendar": {
		"name": "Calendar Mode",
		"secondary": "Calendar Mode specific options",
		"fields": {
			"showLastCalendarWeek": "Show last calendar week",
			"disableCalEventLink": "Disable calendar event link",
			"disableCalLocationLink": "Disable calendar location link",
			"calShowDescription": "Show Description",
			"disableCalLink": "Disable calendar link"
		}
	},
	"appearance": {
		"name": "Appearance",
		"secondary": "Customize the colors etc.",
		"main": {
			"name": "Main",
			"secondary": "Global Color Settings"
		},
		"fields": {
			"dimFinishedEvents": "Dim finished events?"
		}
	}
}
```

**Comment by forreggbor** [comment]
Hi. Here is the translation.


{
  "common": {
    "version": "Verzió",
    "show_warning": "Figyelmeztetés megjelenítése",
    "error": "Hiba",
    "description": "Egy fejlett naptár kártya a Home Assistanthoz Lovelace-al.",
    "fullDayEventText": "Egész nap",
    "untilText": "Amíg",
    "noEventText": "Nincs esemény",
    "noEventsForNextDaysText": "Nincsenek események a kovetkező napokra",
    "hiddenEventText": "az események elrejtve"
  },
  "ui": {
    "common": {
      "previous": "Előző",
      "next": "Következő",
      "week": "hét"
    }
  },
  "errors": {
    "invalid_configuration": "Érvénytelen konfiguráció",
    "update_card": "A naptárat nem lehet Home Assistant komponensből betölteni",
    "no_entities": "Nem adtál meg egyetlen entitást sem"
  },
  "required": {
    "name": "Szükséges",
    "secondary": "A kártya működéséhez szükséges beállítások"
  },
  "main": {
    "name": "Általános beállítások",
    "secondary": "Globálisan alkalmazott beállítások",
    "fields": {
      "name": "Név",
      "showColors": "Színek mutatása",
      "maxDaysToShow": "Max megjelenített napok",
      "showLocation": "Hely ikon megjelenítése",
      "showLoader": "Betöltő animáció megjelenítése",
      "showDate": "Dátum megjelenítése a kártyán",
      "showDeclined": "Elutasított események megjelenítése",
      "sortBy": "Rendezés",
      "allDayBottom": "Az egész napos események megjelenítése legalul",
      "hideFinishedEvents": "Befejezett események elrejtése",
      "dateFormat": "Dátum formátum",
      "hoursFormat": "Idő formátum",
      "defaultMode": "Alapértelmezett mód",
      "linkTarget": "Link cél",
      "refreshInterval": "Frissítési időköz",
      "showRelativeTime": "Relatív idő megjelenítése",
      "firstDayOfWeek": "A hét első napja 0-6",
      "cardHeight": "Kártya magassága",
      "hideDuplicates": "Ismétlődések elrejtése",
      "showMultiDay": "Többnapos események szétválasztása",
      "showMultiDayEventParts": "Többnapos esemény részeinek megjelenítése",
      "eventTitle": "Üres esemény címének meghatározása",
      "compactMode": "Kompakt mód engedélyezése",
      "titleLength": "Cím max hossza (0: végtelen)",
      "descLength": "Leírás max hossza (0: végtelen)",
      "showAllDayEvents": "Egész napos események megjelenítése",
      "offsetHeaderDate": "Fejléc dátum eltolás",
      "startDaysAhead": " Az `x` nap múlva kezdődő események"
    }
  },
  "event": {
    "name": "Esemény mód",
    "secondary": "Esemény módhoz tartozó beállítások",
    "fields": {
      "showCurrentEventLine": "Mutassunk vonalat az esemény előtt?",
      "showProgressBar": "Mutassuk a folyamatjelzőt?",
      "showMonth": "Mutassuk a hónapot?",
      "showWeekDay": "Hét napjainak megjelenítése",
      "showDescription": "Mutassuk a leírást?",
      "disableEventLink": "Az esemény címén lévő link letiltása?",
      "disableLocationLink": "A helyhez kapcsolódó link letiltása?",
      "showNoEventsForToday": "Jelezzük, hogy ma nincs esemény?",
      "showFullDayProgress": "Mutassuk az egésznapos esemény folyamatát?",
      "untilText": "amíg szövege:",
      "noEventText": "Ma nincs esemény szövege:",
      "noEventsForNextDaysText": "A következő napokon nincs esemény szövege:",
      "fullDayEventText": "Egész napos esemény szövege:",
      "showEventIcon": "Esemény ikonjának megjelenítésa",
      "showHiddenText": "Mutassuk a rejtett esemény szöveget?",
      "hiddenEventText": "Rejtett esemény szövege:",
      "showCalendarName": "Naptár nevének megjelenítése",
      "showWeekNumber": "Hét számának megjelenítése",
      "showEventDate": "Esemény dátumának megjelenítése",
      "showDatePerEvent": "Dátum megjelenítése az események mellett",
      "showTimeRemaining": "Hátralévő idő megjelenítése",
      "showAllDayHours": "Egésznapos esemény szöveg megjelenítése",
      "hoursOnSameLine": "Az idő megjelenítése az esemény sorában"
    }
  },
  "calendar": {
    "name": "Naptár mód",
    "secondary": "Naptár módhoz tartozó beállítások",
    "fields": {
      "showLastCalendarWeek": "Az utolsó naptári hét megjelenítése",
      "disableCalEventLink": "Naptár esemény linkjének letiltása",
      "disableCalLocationLink": "Naptár hely linkjének letiltása",
      "calShowDescription": "Leírás megjelenítése",
      "disableCalLink": "Naptár link letiltása"
    }
  },
  "appearance": {
    "name": "Kinézet",
    "secondary": "Színek és egyéb testreszabása",
    "main": {
      "name": "Alap",
      "secondary": "Globális szín beállítások"
    },
    "fields": {
      "dimFinishedEvents": "Befelyezett események elhalványítása?"
    }
  }
}

**Comment by marksie1988** [comment]
Please test on latest beta that this works

**Comment by tanker11** [comment]
Hello,

May I suggest some changes due to grammar or mistypint, sorry.

{
"common": {
"version": "Verzió",
"show_warning": "Figyelmeztetés megjelenítése",
"error": "Hiba",
"description": "Egy fejlett naptár kártya a Home Assistanthoz Lovelace-al.",
"fullDayEventText": "Egész nap",
"untilText": "Amíg",
"noEventText": "Nincs esemény",
"noEventsForNextDaysText": "Nincsenek események a következő napokra",
"hiddenEventText": "az események elrejtve"
},
"ui": {
"common": {
"previous": "Előző",
"next": "Következő",
"week": "hét"
}
},
"errors": {
"invalid_configuration": "Érvénytelen konfiguráció",
"update_card": "A naptárat nem lehet Home Assistant komponensből betölteni",
"no_entities": "Nem adtál meg egyetlen entitást sem"
},
"required": {
"name": "Szükséges",
"secondary": "A kártya működéséhez szükséges beállítások"
},
"main": {
"name": "Általános beállítások",
"secondary": "Globálisan alkalmazott beállítások",
"fields": {
"name": "Név",
"showColors": "Színek mutatása",
"maxDaysToShow": "Max megjelenített napok",
"showLocation": "Hely ikon megjelenítése",
"showLoader": "Betöltő animáció megjelenítése",
"showDate": "Dátum megjelenítése a kártyán",
"showDeclined": "Elutasított események megjelenítése",
"sortBy": "Rendezés",
"allDayBottom": "Az egész napos események megjelenítése legalul",
"hideFinishedEvents": "Befejezett események elrejtése",
"dateFormat": "Dátum formátum",
"hoursFormat": "Idő formátum",
"defaultMode": "Alapértelmezett mód",
"linkTarget": "Link cél",
"refreshInterval": "Frissítési időköz",
"showRelativeTime": "Relatív idő megjelenítése",
"firstDayOfWeek": "A hét első napja 0-6",
"cardHeight": "Kártya magassága",
"hideDuplicates": "Ismétlődések elrejtése",
"showMultiDay": "Többnapos események szétválasztása",
"showMultiDayEventParts": "Többnapos esemény részeinek megjelenítése",
"eventTitle": "Üres esemény címének meghatározása",
"compactMode": "Kompakt mód engedélyezése",
"titleLength": "Cím max hossza (0: végtelen)",
"descLength": "Leírás max hossza (0: végtelen)",
"showAllDayEvents": "Egész napos események megjelenítése",
"offsetHeaderDate": "Fejléc dátum eltolás",
"startDaysAhead": " Az x nap múlva kezdődő események"
}
},
"event": {
"name": "Esemény mód",
"secondary": "Esemény módhoz tartozó beállítások",
"fields": {
"showCurrentEventLine": "Mutassunk vonalat az esemény előtt?",
"showProgressBar": "Mutassuk a folyamatjelzőt?",
"showMonth": "Mutassuk a hónapot?",
"showWeekDay": "Hét napjainak megjelenítése",
"showDescription": "Mutassuk a leírást?",
"disableEventLink": "Az esemény címén lévő link letiltása?",
"disableLocationLink": "A helyhez kapcsolódó link letiltása?",
"showNoEventsForToday": "Jelezzük, hogy ma nincs esemény?",
"showFullDayProgress": "Mutassuk az egész napos esemény folyamatát?",
"untilText": "amíg szövege:",
"noEventText": "Ma nincs esemény szövege:",
"noEventsForNextDaysText": "A következő napokon nincs esemény szövege:",
"fullDayEventText": "Egész napos esemény szövege:",
"showEventIcon": "Esemény ikonjának megjelenítése",
"showHiddenText": "Mutassuk a rejtett esemény szöveget?",
"hiddenEventText": "Rejtett esemény szövege:",
"showCalendarName": "Naptár nevének megjelenítése",
"showWeekNumber": "Hét számának megjelenítése",
"showEventDate": "Esemény dátumának megjelenítése",
"showDatePerEvent": "Dátum megjelenítése az események mellett",
"showTimeRemaining": "Hátralévő idő megjelenítése",
"showAllDayHours": "Egész napos esemény szöveg megjelenítése",
"hoursOnSameLine": "Az idő megjelenítése az esemény sorában"
}
},
"calendar": {
"name": "Naptár mód",
"secondary": "Naptár módhoz tartozó beállítások",
"fields": {
"showLastCalendarWeek": "Az utolsó naptári hét megjelenítése",
"disableCalEventLink": "Naptár esemény linkjének letiltása",
"disableCalLocationLink": "Naptár hely linkjének letiltása",
"calShowDescription": "Leírás megjelenítése",
"disableCalLink": "Naptár link letiltása"
}
},
"appearance": {
"name": "Kinézet",
"secondary": "Színek és egyéb testreszabása",
"main": {
"name": "Alap",
"secondary": "Globális szín beállítások"
},
"fields": {
"dimFinishedEvents": "Befejezett események elhalványítása?"
}
}
}

MagicF ***@***.***> ezt írta (időpont: 2023. okt. 20., P,
15:26):

**Comment by forreggbor** [comment]
You're right about the typo and grammer mistakes. Thanks for correcting. :-)

**Comment by forreggbor** [comment]
> Please test on latest beta that this works

Hi. 
I tested with v9.2.0-beta2. Looks good but the date format in Hunagry is like YYYY. MM dd. (2023. október 23.). Is it possible to display like this? As I saw the days.js is not supporting such display format.
