### ISSUE TITLE
Text formatting breaks description display

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [totaldebug/atomic-calendar-revive#511]
If text formatting is used in event description, HTML entities are escaped, which leads to an unreadable mess.

## Expected behaviour
Text formatting should be displayed, or at least plain text should be shown instead.

## Current behaviour
All HTML entities are escaped, which makes it hard to read the description, and makes it impossible to use formatting.

## Screenshot
How it looks in Google Calendar:
![изображение](https://user-images.githubusercontent.com/928550/137593837-8697ed6e-3d2d-4fcf-a14b-c6fd9b67d630.png)

How it looks in ACR:
![изображение](https://user-images.githubusercontent.com/928550/137593462-eb5fd9a1-3a77-428e-b2c4-3a26b983d3fc.png)

## Possible reasons and solutions
I suggest introducing a new option to select between 3 modes: 1) leave everything as-is 2) allow HTML in description 3) strip HTML and only leave plain text (although <br> should be converted to line breaks)

## Steps to reproduce

1. Create an event in Google Calendar
2. Write some description that uses text formatting
3. See the bug

A very basic config reproduces this bug:
```
type: custom:atomic-calendar-revive
calShowDescription: true
entities:
  - entity: calendar.daily_biz
showDescription: true
```

## Context
I wanted to use text formatting to cross out text in the description, as an improvised to-do list. Unfortunately this is impossible due to this issue.

## Your environment
ACR 5.0.0
Home Assistant 2021.10.5

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [x] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.

**Comment by marksie1988** [comment]
Hi @ZimM-LostPolygon, 

I have taken a look at this and I haven't been able to get the HTML to render, I assume that this is a security feature as modern browsers automatically convert this string.

the feature of ES6 that would do this is deprecated and not recommended so I would need to look into another solution if this is possible. 

It is also potentially quite risky if someone were to place some malicious code in a calendar entry it would execute so im not sure its a good idea to do this.

**Comment by marksie1988** [comment]
Yea it does come un-escaped, I have re-encoded it but still won't render correctly. I wasn't able to find a way to get it to render.

**Comment by donnib** [comment]
Any progress on this ?
