### ISSUE TITLE
2021.11.0 causes error

### ISSUE THREAD

**Issue by Sholofly** [totaldebug/atomic-calendar-revive#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Enabling the plugin leads to an error on my auto-generated dashboard preventing cards to load.

![image](https://user-images.githubusercontent.com/901632/139219625-34c133dd-dc95-4b38-a720-2642574bc52b.png)

### Expected behaviour

No errors in the console, loading al cards on my dashboard

### Steps To Reproduce

1. Enable this plugin
2. Open auto-generated dashboard
3. OPen dev-tools

### Card Version

latest

### Home Assistant Version

2021.11.0b

### Configuration

```shell
No specific configuration, Card is not visible on my auto-generated dashboard
```

### Relevant log output

```shell
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-linear-progress" has already been used with this registry
    at http://homeassistant.local:8123/frontend_latest/app.7f90204d.js:1243:6875
    at http://homeassistant.local:8123/frontend_latest/app.7f90204d.js:1243:6890
    at a (http://homeassistant.local:8123/frontend_latest/app.7f90204d.js:850:118198)
    at Object.62744 (http://homeassistant.local:8123/frontend_latest/f4070540.js:28:11255)
    at u (http://homeassistant.local:8123/frontend_latest/app.7f90204d.js:1243:29185)
    at Module.13525 (http://homeassistant.local:8123/frontend_latest/e5714b15.js:1:507)
    at Function.u (http://homeassistant.local:8123/frontend_latest/app.7f90204d.js:1243:29185)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skynetua** [comment]
Fix works, thanks

**Comment by marksie1988** [comment]
I will be releasing v6 of the card today which will resolve issues made from the 2021.11 release

**Comment by Sholofly** [comment]
Thanks @marksie1988! Works like a charm!
