### ISSUE TITLE
Card not working with cast

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to use the card casted to a nest hub it is not showing

### Expected behaviour

Card should show up on the nest hub

### Steps To Reproduce

1. have card installed
2. cast to nest hub
3. see if card is showing

### Card Version

5.2.2

### Home Assistant Version

2021.10.6

### Configuration

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Svanberg1** [comment]
I am having this issue as well, anyone have any ideas of how to fix it?

**Comment by marksie1988** [comment]
I'm afraid at the moment I have no where to test this. I'm trying to get mine working again but not had the time.

**Comment by funhop1** [comment]
Same here, when i use the cast in the automation with "play_media" the calendar is not showed. 
What i noticed when using catt :
As a shell command, https://my.duckdns.org/card/view/: the card itself is showed, but data could not be showed in home-assistant But when using the url http://192.168.x.x:8123/card/view it is working correct.

Not knowing the above could help, but just wanted to inform :) (cors / url etc?)

**Comment by marksie1988** [comment]
I have tested with the latest version and can confirm this issue has been resolved in the pre-release - v7.0.0-b1 

If you would like you can install the pre-release and then let me know if you see any issues.
