### ISSUE TITLE
Atomic Calendar Revive prevents Media Control Card from loading in HA 2021.11.0

### ISSUE THREAD

**Issue by ResteNarquois** [totaldebug/atomic-calendar-revive#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lovelace tabs with the core HA Media Control Card will not load the card if the Atomic Calendar Revive card has already been loaded in another tab. If you load a tab with a Media Control Card first, then ACR will not load.

The debug window in Firefox 94.0 shows this error:

'Uncaught (in promise) DOMException: CustomElementRegistry.define: 'mwc-linear-progress' has already been defined as a custom element'

Removing the ACR card from Lovelace resources fixes the issue.

### Expected behaviour

I would expect both cards to load without issues

### Steps To Reproduce

1. Lovelace dashboards using standard Media Control Card and Atomic Calendar Revive Card
2. Using Firefox 94.0 web browser
3. Load dashboards into web browser
4. Firefox debug window shows this error: 'Uncaught (in promise) DOMException: CustomElementRegistry.define: 'mwc-linear-progress' has already been defined as a custom element'
5. Removing the ACR card from Lovelace resources allows the Media Control card to function as normal

### Card Version

6.02b

### Home Assistant Version

2021.11.0

### Configuration

```shell
################################################################################
  ##============================= LOVELACE TEST ============================##
################################################################################

title: Test
icon: mdi:home-assistant
path: test
cards:
  - type: media-control
    entity: media_player.sitting_room_universal
```

### Relevant log output

```shell
Uncaught (in promise) DOMException: CustomElementRegistry.define: 'mwc-linear-progress' has already been defined as a custom element
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ResteNarquois** [comment]
Link to post on HA community forum with screenshots:

[https://community.home-assistant.io/t/2021-11-icon-picker-device-links-and-entity-categories/352836/172?u=reste_narquois](url)

**Comment by Pierrodu21** [comment]
Same issue here: https://github.com/totaldebug/atomic-calendar-revive/issues/525

With screenshots

**Comment by marksie1988** [comment]
The current version of the card is not compatible with v2021.11.0 of HA due to some changes made. 

I am doing a release shortly please see #519 where this is being tracked.
