### ISSUE TITLE
Declined events not styled in event mode when links disabled

### ISSUE THREAD

**Issue by alainperry** [totaldebug/atomic-calendar-revive#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an event is marked as declined, it is styled accordingly in "calendar mode" (shallow bullet). However, in "event mode", the same event is styled (strike-through) only if it has a link and links are not disabled.

### Expected behaviour

Event title should be style according to its "declined" status whether links are disabled or not.

I believe the bug is [here](https://github.com/totaldebug/atomic-calendar-revive/blob/adfa34a93a9b8f9887fecf90e93eefb80314aa25/src/index.ts#L617).

### Steps To Reproduce

1. Add a calendar with disabled events
2. Disable links in card config
3. Display calendar in "event mode"
4. Check that declined events are visually indistinguishable from other events

### Card Version

v6.0.0

### Home Assistant Version

2021.10.6

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar name
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 1
refreshInterval: 60
entities:
  - entity: calendar.xxx
    icon: mdi:icon
showDate: false
sortByStartTime: true
showRelativeTime: false
showMonth: false
showWeekDay: true
showProgressBar: true
disableEventLink: true
disableLocationLink: true
showNoEventsForToday: true
showEventIcon: false
showHiddenText: false
showDescription: true
showCurrentEventLine: false
calShowDescription: true
showLastCalendarWeek: true
disableCalEventLink: true
disableCalLocationLink: true
disableCalLink: true
showDeclined: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I will look into this, however please note v6.0.0 is only supported on 2021.11 Upwards so you may see some issues because of this, mainly with the progress bar though
