### ISSUE TITLE
Maybe changes in HACS lead to issues

### ISSUE THREAD

**Issue by Pirol62** [totaldebug/atomic-calendar-revive#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A picture tells more then 1000 words:
![image](https://user-images.githubusercontent.com/48820003/142186631-45a58ae5-efd6-4657-a300-b398b30e73ca.png)
The update button is frozen:
![image](https://user-images.githubusercontent.com/48820003/142186728-aeb61015-5836-4d2e-badc-d59c6cfdeb5e.png)
The description cannot be loaded
![image](https://user-images.githubusercontent.com/48820003/142186814-2cffb452-2a57-409d-ba98-c044a9737c4f.png)

### Expected behaviour

usual behavior

### Card Version

latest

### Home Assistant Version

2021.10.6

### Configuration

```shell
not related to this issue
```

### Relevant log output

```shell
`
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hacs
Source: custom_components/hacs/api/hacs_repository.py:108
Integration: HACS (documentation, issues)
First occurred: 11:47:59 (2 occurrences)
Last logged: 11:48:41

Could not use repository with ID 0 ('NoneType' object has no attribute 'data')
````
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pirol62** [comment]
For me, after a restart, everything is fine again. I could successfully update the component.

**Comment by G0RIAN** [comment]
A plain restart didn't change anything for me. Howevere manually downloading the `/dist/atomic-calendar-revive.js` to `/config/www/community/atomic-calendar-revive/` and restarting HA afterwards allowed me to reinstall the component over HACS.

**Comment by dedors** [comment]
I had the exact same behavior as @G0RIAN reported.

To solve it I skipped the download step and just deleted the `/config/www/community/atomic-calendar-revive/` folder. That gave a warning in HACS after a restart, but I could proceed with the update successfully.

**Comment by marksie1988** [comment]
> I had the exact same behavior as @G0RIAN reported.
> 
> To solve it I skipped the download step and just deleted the `/config/www/community/atomic-calendar-revive/` folder. That gave a warning in HACS after a restart, but I could proceed with the update successfully.

Nice thanks for the update this will help for any others with this issue.
