### ISSUE TITLE
Is there any way to show the calendar name for each event (in the Events view)?

### ISSUE THREAD

**Issue by ndbroadbent** [totaldebug/atomic-calendar-revive#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No calendar name is shown

### Expected behaviour

I would like an option to add the calendar name for each event, so that I know which calendar each event is coming from

### Possible Solutions

A new option to show the calendar name as some small text below or next to the event name

### Context / Reason

My wife and I have multiple calendars that are all shown on the same calendar widget on a dashboard screen. This would be very useful

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ndbroadbent** [comment]
I'm taking a look at the source code and doing some debugging, and it looks like `eventCalName` isn't present anymore in `event._config.eventCalName`. I'm only seeing an `entity` property here:

```
_config:
  entity: "calendar.family"
```

**Comment by ndbroadbent** [comment]
Cool, that fixed it for me!

I updated the `const eventCalName = ...` lines in `index.ts` to this:

```
				//show calendar name
				let calDisplayName = event._config.eventCalName
				if (!calDisplayName) {
					if (event.eventClass && event.eventClass.organizer) {
						const eventOrganizer = event.eventClass.organizer
						calDisplayName = eventOrganizer.displayName || eventOrganizer.email
					}
				}
				const eventCalName = calDisplayName
					? html`<div class="event-cal-name" style="color: ${calColor};">
							<ha-icon icon="mdi:calendar" class="event-cal-name-icon"></ha-icon>&nbsp;${calDisplayName}
					  </div>`
					: ``;
```

Starts by checking `event._config.eventCalName` (current behavior), then falls back to `event.eventClass.organizer.displayName` and `event.eventClass.organizer.email` if they are present. Now I've got the calendar names working again.

**Comment by marksie1988** [comment]
Thanks for this, I will look at adding this back into the card in some form. 

This was removed when icons were added as they can be used in both Calendar and event mode
