### ISSUE TITLE
Strange start/end times

### ISSUE THREAD

**Issue by WonderMoose** [totaldebug/atomic-calendar-revive#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my list of events, the start and end times have some numbers I cant quite decipher. 

Example is an event tomorrow which starts at 10:45 and ends at 11:45. The card shows: 2410-2411
I am running with 24h on v. 6.1.2

### Expected behaviour

The start time should show 10:45 and the end time should show 11:45

### Steps To Reproduce

Its consistent 

### Card Version

6.1.2

### Home Assistant Version

core-2021.12.4

### Configuration

```shell
type: custom:atomic-calendar-revive
europeanDate: true
hoursFormat: 24h
entities:
  - entity: calendar.torben_kalender
    color: orange
  - entity: calendar.louise
    color: green
    blacklist: tømmes
  - entity: calendar.men_with_manners
    color: red
timeColor: grey
dimFinishedEvents: true
calShowDescription: false
disableCalLink: false
showProgressBar: false
showCurrentEventLine: false
showMonth: false
showWeekDay: true
showFullDayProgress: true
showEventIcon: false
showHiddenText: false
fullDayEventText: Hele dagen
untilText: Indtil
noEventsForNextDaysText: Ingen aftaler
noEventText: Ingen aftaler
firstDayOfWeek: 1
maxDaysToShow: 7
refreshInterval: 60
dateFormat: LL
showRelativeTime: true
hideFinishedEvents: false
showDeclined: false
showLoader: true
showDate: true
sortByStartTime: false
showHours: true
showNoEventDays: true
hideDuplicates: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
please remove below from your config, this setting was changes a few versions back due to changes in HA

```
hoursFormat: 24h
```

**Comment by WonderMoose** [comment]
Oh sorry, i must have missed that. Thanks a lot
