### ISSUE TITLE
[FR] Next event at sunset

### ISSUE THREAD

**Issue by pex81** [totaldebug/atomic-calendar-revive#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Is it possible to set that at sunset to display the events of the day after, in the style of the apple calendar widget?

### Expected behaviour

I don't find an option to say that the day ends at 6pm for example.

### Context / Reason

I mainly use the app to view work events, and therefore at the end of the working day, I would like to view those of the following day and not view those of the current day until 00:00

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hey there, I don't have the apple calendar widget so unsure what that does / looks like. 

So basically you want to say after x time show me the next day's events? Could you not show 2 days instead?

**Comment by pex81** [comment]
<img width="292" alt="Schermata 2022-01-04 alle 19 48 14" src="https://user-images.githubusercontent.com/58252398/148108914-0485eb5f-36b5-404d-bc97-501cced5f7ba.png">
This is an example of my card, I don't have much space, Event1 and Event2 are the events but I would like to see those of the next day after 6pm.
