### ISSUE TITLE
Eventmode: Separator between calendar weeks 

### ISSUE THREAD

**Issue by baggy13** [totaldebug/atomic-calendar-revive#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A flatten list of appointments. 

### Expected behaviour

Would be nice to have a separator between calendar weeks. 

### Possible Solutions

New flag like 'showCalendarWeekLabel'.

E.g.
![Screenshot_20220116_163639](https://user-images.githubusercontent.com/87035352/149666777-271dc433-5db7-4311-9fdb-92b76f30ad13.jpg)

And maybe a little margin-top to previous calendar week. 

### Context / Reason

Should help to have a clear overview about upcoming events in the next weeks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hey, 
Do you mean add a text at the begining of a week saying `week 7`

Please let me know if I understood correctly.

**Comment by baggy13** [comment]
Hey @marksie1988,

yes you got it correctly. If possible with some extra top paddings to get the weeks just a bit separated from each other and have a cleaner overview about several weeks at the same time.

Thanks for taking this task in account.

BR
