### ISSUE TITLE
Hide date

### ISSUE THREAD

**Issue by Cassock** [totaldebug/atomic-calendar-revive#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Events all show numeric date to the left. 

### Expected behaviour

For users that only show 1 day of events at a time, it would be nice to hide this date and just show the events. 

### Possible Solutions

Add toggle to display date (just as there is for month and day).

### Context / Reason

For users that only show 1 day of events at a time, it would be nice to hide this date and just show the events. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Cassock** [comment]
Having a 'Today' and 'Tomorrow' designation might be nice, but that may be a better case for markdowncard+template.

**Comment by Cassock** [comment]
Looks like `dateSize: 0` may be what I'm after.

**Comment by marksie1988** [comment]
Hi, could you possibly attach a screenshot of which date you are referring to, there are multiple locations that the dates are shown.
