### ISSUE TITLE
Link if calendar can't be loaded is wrong

### ISSUE THREAD

**Issue by scharmach** [totaldebug/atomic-calendar-revive#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![grafik](https://user-images.githubusercontent.com/9080980/152224156-cfa1faf4-041e-438a-8c30-64b88c17605d.png)

Clicking "See Here" goes to https://marksie1988.github.io/atomic-calendar-revive/faq.html and this site doesn't exist anymore.

### Expected behaviour

It should link to the correct FAQs, which seem to be: https://docs.totaldebug.uk/atomic-calendar-revive/faq.html

### Card Version

6.2.0

### Home Assistant Version

2021.12.10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Thanks for logging this, I will get this updated in the next release 👍
