### ISSUE TITLE
Editor not easily downloadable

### ISSUE THREAD

**Issue by benv666** [totaldebug/atomic-calendar-revive#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[The quickstart](https://docs.totaldebug.uk/atomic-calendar-revive/quickstart.html) states:
```
If you use Lovelace and want to use the editor, download the atomic-calendar-revive-editor.js to /www/community/atomic-calendar-revive/. (or the folder you used above)
```
However, this file is nowhere to be found. [Google can't find it](https://www.google.com/search?q=%22atomic-calendar-revive-editor.js), and I really don't want to get bugged down by manually having to compile this.
So the real question is: Why is this not included in the default distribution to begin with?

### Expected behaviour

Click install in HACS, edit lovely, have a working card.

### Steps To Reproduce

1. Download card through HACS.
2. Wonder how to add card through Lovelace
3. Read quickstart
4. ????
5. Profit.

### Card Version

v6.2.0

### Home Assistant Version

2022.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hey there, seems I need to update the documentation...

The editor is included in the card now, when you install with hacs it will have the editor

**Comment by benv666** [comment]
While that's good to hear, I do not see the editor anywhere.

![image](https://user-images.githubusercontent.com/165034/153649128-e6887e13-2455-4b2a-97f0-02828f756411.png)
![image](https://user-images.githubusercontent.com/165034/153649085-281eeed1-eec2-4df6-8641-cd6310ef3013.png)

Yet it's in ui-lovelace:
![image](https://user-images.githubusercontent.com/165034/153649226-ce533eb7-fd8a-4490-b547-7d975dc24afc.png)
and home assisstant was restarted afterwards.
Suggestions?

**Comment by benv666** [comment]
Ok, scratch that - it works after a few hard reloads, browser cache :-)
Thanks for the support! Will leave this open so you can update your docs though.

**Comment by marksie1988** [comment]
Thanks, glad that it's working for you now.
