### ISSUE TITLE
Hiding some numbers

### ISSUE THREAD

**Issue by planet4** [totaldebug/atomic-calendar-revive#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I do not really understand what some numbers are. For example 2411-2412. I have tried all options to hide these.

![image](https://user-images.githubusercontent.com/22392924/155483575-f224de72-6b99-444d-866c-735df2d501a4.png)

### Expected behaviour

I would like to know if they can be hidden

### Context / Reason

Not sure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi there, 

please remove below from your config, this setting was changes a few versions back due to changes in HA

`hoursFormat: 24h`
