### ISSUE TITLE
Show calendar source for each calendar

### ISSUE THREAD

**Issue by manuelo1983** [totaldebug/atomic-calendar-revive#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now I use this calendar view for 3 different calendars. The calendar for my wife, the one for me and then one for the family.
But in the overview view you can't distinguish which entry belongs to which calendar.

### Expected behaviour

It would be nice if you could see the name of the calendar behind an entry in brackets or if you could assign a name to each calendar, which is then displayed accordingly.

### Possible Solutions

It would be nice if you could see the name of the calendar behind an entry in brackets or if you could assign a name to each calendar, which is then displayed accordingly.

### Context / Reason

The whole thing is simply for clarity and would help enormously.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi @manuelo1983,

If you use event view you can add the option `showEventIcon` which will show the calendar icon, this option will change slightly in v7 but will be documented. 

Also in v7 you will be able to add a calendar name, and choose if that is displayed. 

If you use calendar mode, currently there is no option to show the icon on the summary, only in the calendar view. Please let me know if that's the mode you use

**Comment by BebeMischa** [comment]
We use those icons, and different text colors to see the differences ;-)

**Comment by manuelo1983** [comment]
Thank you. That helps me. @BebeMischa One other question. Is it possible to make e.g. the title with color and bold?

**Comment by marksie1988** [comment]
I usually recommend using card-mod which allows changing the styles of cards to whatever you need, this saves me adding hundreds of options for colours/ typeface etc. This is how I would recommend doing what you like. 

The options that exist for colours at the moment we're legacy.
