### ISSUE TITLE
maxEventCount not working

### ISSUE THREAD

**Issue by jjprz** [totaldebug/atomic-calendar-revive#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have updated to the latest version and "maxEventCount" does not work. "hideFinishedEvents" doesn't work either

### Expected behaviour

It is showing all available events without limit

### Card Version

7.0.0-b2

### Home Assistant Version

2022.3.1

### Configuration

```shell
- type: custom:atomic-calendar-revive
            name: 'Next events'
            showMonth: true
            showWeekDay: true
            showDescription: true
            disableLocationLink: true
            refreshInterval: 600
            europeanDate: true
            showRelativeTime: false
            showProgressBar: false
            maxDaysToShow: 60
            maxEventCount: 3
            timeSize: 80
            hideFinishedEvents: true
            entities:
            - entity: calendar.sports
              allowlist: 'Betis'
```

### Relevant log output

```shell
Nothing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
@jjprz  please checkout the new pre-release 7.0.0-b3 which resolves both of these issues.
