### ISSUE TITLE
Calendar Event Times Not Displaying Properly

### ISSUE THREAD

**Issue by j6s33m** [totaldebug/atomic-calendar-revive#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All my calendar events are pulling in fine, but I haven't had the times working properly for at least a month now. I had hoped it would be fixed in an update, but unfortunately it has not been yet. As you'll see in the image...the times are just some numbers that start with 1, but don't make sense or translate to anything.

<img width="497" alt="Screen Shot 2022-03-12 at 3 43 35 PM" src="https://user-images.githubusercontent.com/17929290/158036207-b37a421e-0c8e-4fb8-853b-1d1ae3245f7b.png">

### Expected behaviour

I expect the actual times to show up.

### Card Version

6.2.0

### Home Assistant Version

2023.3.3

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - calendar.birthdays
  - calendar.family
  - calendar.personal
showMonth: false
showWeekDay: true
showLoader: true
showDate: true
initial_view: dayGridMonth
maxDaysToShow: 7
sortByStartTime: true
showDescription: false
showCurrentEventLine: false
showNoEventsForToday: true
showEventIcon: false
showFullDayProgress: true
calShowDescription: false
showLastCalendarWeek: false
showRelativeTime: true
showDeclined: false
hideFinishedEvents: false
showProgressBar: true
name: Family Calendar
firstDayOfWeek: 1
showLocation: true
showHiddenText: false
dimFinishedEvents: true
disableLocationLink: false
refreshInterval: 15
dateFormat: LL
hoursFormat: 12h
disableCalEventLink: false
disableCalLocationLink: false
hideDuplicates: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Please see FAQ here: [unusual time format](https://docs.totaldebug.uk/atomic-calendar-revive/overview/faq.html#unusual-numbers-where-time-should-be-located)

**Comment by j6s33m** [comment]
TY! Making that change and a restart to HA solved it. Much appreciated
