### ISSUE TITLE
Add text to event title

### ISSUE THREAD

**Issue by ajobbins** [totaldebug/atomic-calendar-revive#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The title for the event shown on the Calendar card is exactly as it recorded in the 'Message' attribute of the calendar entry in HA.

### Expected behaviour

The ability to add some text before and/or after the text recorded against the event message in HA to be displayed on the Atomic Calendar Revive card

### Possible Solutions

Fields at the Entity level to set a static string to be prefixed to or appended to the 'Message' text that is displayed for the calendar entry

### Context / Reason

I currently have a work calendar fed in HA via my personal Google account (i.e. it's Shared from my work Google account to my personal). I can't (policy) connect my work calendar directly to HA, and my sharing is limited to free/busy only. This means that all my "work" calendar events have no title in HA to show on the Calendar. I don't actually need the real event name, as the use case for this card is for my family to see when I have work meetings - but what those meetings are have no relevance (So in this case, it's essentially better for me to only have free/busy coming across).

I'd like to be able to add some text to events on that calendar so that instead of being blank, they could say "Work Meeting" or whatever I needed.

I've proposed a more generic solution because while the solution should also solve the issue I have of 'Blank' meeting names (only times show) for my work Calendar, there may be other situations where you may want to add some context to an event title.

An alternative (or additional) solution more specific to my use case would be to have a field at the entity level to set the text to show where the 'Message' attribute was blank for an event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi, my upcoming release will include a new option to add a title to blank entries, is this sufficient? 

I can add an appendix to the front of each title but not sure that is worth the effort if the above is enough  

Same as #972

**Comment by ajobbins** [comment]
Yep this is good. Thanks!
