### ISSUE TITLE
I believe some changes you made here have broken startTimeFilter and endTimeFilter.  When they are set, no entries from that calendar are shown.

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#715]
I believe some changes you made here have broken startTimeFilter and endTimeFilter.  When they are set, no entries from that calendar are shown.  

```
    startTimeFilter: '00:01'
    endTimeFilter: '23:59'
```

Should show all entries that aren't all-day events but instead show nothing at all.   

Version 7.0.0

_Originally posted by @BoredMind in https://github.com/totaldebug/atomic-calendar-revive/issues/704#issuecomment-1162279402_

**Comment by ajobbins** [comment]
FWIW, the changes in 7.0.0 worked for me, and i just tried changing the filter to the same values above and I see all calendar entries for that day

**Comment by marksie1988** [comment]
@BoredMind could you please share your card configuration for me to see what's happening? 

As AJ states it works for him and I also have it working.

**Comment by marksie1988** [comment]
Tested and this is working as expected, closing
