### ISSUE TITLE
Combining maxEventCount and maxDaysToShow loses calendars

### ISSUE THREAD

**Issue by Hanien1977** [totaldebug/atomic-calendar-revive#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When combining maxEventCount and maxDaysToShow, I seem to lose calendars.

I have 5 calendard, 4 icloud and 1 google calendar shown in Home Assistant.

When only setting maxDaysToShow, I get all calendars shown in Atomic, but combining the options I only get some of the calendars.
Which calendars I lose, depends on the combination changes when refreshing, but it never shows all at once.

I think I am hitting som logic, but can't figure out what.

My problem is, that my dashboard can only show 15 events. The problem could be solved by setting MaxEvents to 15, but not setting MaxDays sets it to default 7 days and I rarely have my 15 events within the next 15 days :) so the 15 events gets cut of 7 days forward.

### Expected behaviour

I expect to the able to combine the two options without losing calendars

### Card Version

7.0.0

### Home Assistant Version

2022.6.7

### Configuration

```shell
- type: custom:atomic-calendar-revive
            style:
              top: 39%
              left: 38.5%
              width: 27%
            title: true
            progressBar: true
            showCalendarName: true   
            maxDaysToShow: 8
            language: da
            showMonth: true
            showWeekDay: true
            showLoader: false
            showProgressBar: false
            dateTopFormat: DD/MM
            dateBottomFormat: dddd
            highlightToday: true
            showDescription: false           
            europeanDate: true
            eventTitleSize: 150
            dateSize: 130
            entities:             
              - entity: calendar.freya
                name: Freya
              - entity: calendar.gosia
                name: Gosia
              - entity: calendar.laerke
                name: Lærke
              - entity: calendar.jonas
                name: Jonas
              - entity: calendar.familien
                name: Familien 
                color: red                
              - entity: calendar.https_services_tamigo_com_calendar_0b03dfd4_a2dc_4b72_8958_f5f186913eb7_calendar_ics
                name: McD  
                color: yellow
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi There, 

I'm just trying to understand what you expect to see? in your config you dont have `maxEventCount` set so im not sure what you expect to see? 

e.g. do you expect to see 15 events over a maximum of 15 days? 

I have tested with the below settings and it loads perfect each time:

```
maxDaysToShow: 8
maxEventCount: 3
```

If  you could give an example of what you see vs what you expect to see that would help.

thanks

**Comment by Hanien1977** [comment]
I have been struggling with this for the past month, but when trying to recreate everything suddenly work.
The only solution I can come up with is the order of the options.

I will keep an eye on it for a couple of day and comment if the problem persists

**Comment by majdzik84** [comment]
I have the same problem. I have 3 calendars and noticed similar behavior to @Hanien1977

**Comment by marksie1988** [comment]
Hi, Please could you confirm if you still see this issue with v7.5.0?

**Comment by marksie1988** [comment]
As there has been no response I'm closing this
