### ISSUE TITLE
Week numbers may be wrong

### ISSUE THREAD

**Issue by LordMike** [totaldebug/atomic-calendar-revive#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Denmark, the week number 1 starts on the first week with 4 days in the new year. This means that right now, 2022-06-23 is week 25, while this calendar card says week 26.

![image](https://user-images.githubusercontent.com/1027111/175407856-d98ad21d-73b7-40ea-b40e-18674c5ddc7b.png)

You can compare this with [ugenr.dk](https://ugenr.dk/), which shows the current week number.

### Expected behaviour

I was expecting a setting that could configure this behavior, but I couldn't find anything (besides which day was the first day of the week.

I'm hoping that something like `moment` would be able to handle this. I checked on a device with danish locale, and it also showed week 26, so it's not applying currently.

### Steps To Reproduce

Should occur always, at least for Danish users.

### Card Version

v7.0.0

### Home Assistant Version

2022.6.6

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - calendar.my_calendar
showCalendarName: true
showWeekDay: true
sortByStartTime: true
showDate: true
dateFormat: dddd, DD MMMM HH:mm
hoursFormat: HH:mm
maxDaysToShow: 6
refreshInterval: 60
showWeekNumber: true
disableLocationLink: true
disableEventLink: true
showNoEventsForToday: true
dimFinishedEvents: true
fullDayEventText: Hele dagen
noEventText: Ingen events
showProgressBar: false
hideFinishedEvents: true
showRelativeTime: true
hideDuplicates: true
showMultiDay: true
showMultiDayEventParts: true
showCurrentEventLine: false
noEventsForNextDaysText: Ingen kalender info
firstDayOfWeek: 1
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LordMike** [comment]
Additionally, when the current locale is danish, "Week" isn't translated.. :)

**Comment by marksie1988** [comment]
Ok I have released a new version, can you install, and then in the browser console you should see the new version plus the language it thinks it should be using: 

![Image](https://user-images.githubusercontent.com/159166/175833653-de86a0a0-c52d-45a7-8755-8981345454b0.png)

Let me know what you get on here and I will check the card is loading the correct things for this, also if you could let me know under your user, what is the name of the language you have selected, I assume either Dansk or Deutsch?

**Comment by AdmiralStipe** [comment]
Not sure if you saw my comment on PR 720... the new translation in sl.json for week is incorrect - can you please check and correct it?

**Comment by LordMike** [comment]
> Ok I have released a new version, can you install, and then in the browser console you should see the new version plus the language it thinks it should be using:
> 
> ![Image](https://user-images.githubusercontent.com/159166/175833653-de86a0a0-c52d-45a7-8755-8981345454b0.png)
> 
> Let me know what you get on here and I will check the card is loading the correct things for this, also if you could let me know under your user, what is the name of the language you have selected, I assume either Dansk or Deutsch?

Updated, and it now says "Uge" (yay)

It reports "da".

![image](https://user-images.githubusercontent.com/1027111/176428623-0c8c029b-9759-4f1f-b54f-26ccbfb9e614.png)

**Comment by csabatth** [comment]
Hello, I'm experiencing the same issue. It seems if only the "en-gb" version shows the "correct" week number and all the other ones   don't. I'm using "en-gb" and "hu". I assume that the only workaround is to set HA local to en-gb and reinstall the component or are there other alternatives?

Thank you!

**Comment by marksie1988** [comment]
checked and this appears to be correct: 
![image](https://user-images.githubusercontent.com/159166/209823308-761e85a3-003b-4d76-a43f-e7e6dccdb223.png)
