### ISSUE TITLE
Option to hide past events in event mode

### ISSUE THREAD

**Issue by DarkFox** [totaldebug/atomic-calendar-revive#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Past events are only greyed out.

### Expected behaviour

There should be an option to hide past events.

### Context / Reason

Currently, there's no option to hide events that have already passed, so if you have a lot of events in your calendar, you might have to scroll down to see the current and upcoming events.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dajomu1** [comment]
How do you add "hideFinishedEvents" to event mode calendar. Using the example from the quick start:
Where does it go?

- type: "custom:atomic-calendar-revive"
   entities:
   - entity: calendar.YOUR_CALENDAR_HERE
     name: 'My Calendar'
     color: red

**Comment by dajomu1** [comment]
Sorry. I totally missed this and ended up using HA calendar.
![image](https://user-images.githubusercontent.com/98491691/197171491-f3c01a0c-cb6c-4877-a90e-9a17391098c8.png)

**Comment by marksie1988** [comment]
docs updated now to include this option, thanks for highlighting.
