### ISSUE TITLE
Progress bar is not styled

### ISSUE THREAD

**Issue by Firesphere** [totaldebug/atomic-calendar-revive#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2022-07-08 at 10-32-31 Overview – Home Assistant](https://user-images.githubusercontent.com/680570/177882625-c2fb4a49-276b-4855-8e47-ab748c4644ce.png)

### Expected behaviour

A more nicely styled progress bar, like before

### Card Version

7.0.1

### Home Assistant Version

2022.7

### Configuration

```shell
- platform: caldav
  username: user@gmail.com
  password: !secret treehouse_caldav
  url: https://example.com/html/dav.php/calendars/user@gmail.com/
  calendars:
    - Simon
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
pro0gress bar style can be set with the following config:

```
progressBarColor: 
progressBarBackgroundColor:
```

or this could be styled with card mod
