### ISSUE TITLE
Calendar mode not showing split multi-day events as expected

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/atomic-calendar-revive#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

calendar mode doesn't show the split multi day events correctly

### Expected behaviour

show icons for split multi- day events

### Card Version

7.0.0

### Home Assistant Version

N/A

### Configuration

```shell
- type: "custom:atomic-calendar-revive"
    name: "My Work Calendar"
    #defaultMode: Calendar
    maxDaysToShow: 21
    showLoader: false
    showMultiDay: true
    showMultiDayEventParts: true
    entities:
      - entity: calendar.my_cal_gmail_com
        type: icon
        icon: mdi:weather-sunny
        color: green
        allowlist: days
      - entity: calendar.my_cal_gmail_com
        type: icon
        icon: mdi:weather-night
        color: red
        allowlist: nights
      - entity: calendar.my_cal_gmail_com
        type: icon
        icon: mdi:star
        color: orange
        allowlist: DD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Tested and it appears to work as expected for the first multiday calendar, however if there are multiple then the icons dont appear. 

This is something to  do with the icon array that is created.

**Comment by Igor01-Tech** [comment]
It's exactly the same for me too. This appeared first after the update to V7+!

Here is a comparison: https://imgur.com/a/CT09uBI
