### ISSUE TITLE
language bug

### ISSUE THREAD

**Issue by rhgiter** [totaldebug/atomic-calendar-revive#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on pc the calendar is in language danish 

when I see the same lovelace side on the app , it is in english

(HA app is in danish)

### Expected behaviour

--

### Steps To Reproduce

--

### Card Version

newest

### Home Assistant Version

neweset

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Please supply your configuration for the calendar card if this is still happening. However if this works on the PC I'm not sure it would be the card with the issue and rather the app doesnt support part of the JS. 

What app are you using that you see in English?

**Comment by marksie1988** [comment]
As there has been no update with further information I am closing this
