### ISSUE TITLE
Multiple Events on a single day in MonthView should be scrollable

### ISSUE THREAD

**Issue by RolandE1204** [totaldebug/atomic-calendar-revive#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the entry is 

+2 additional

### Expected behaviour

make each single day scrollable

### Context / Reason

Having more events on a single day and seeing them without changing the view.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi I'm sorry but this doesn't provide me enough information to understand what you are looking for.

**Comment by RolandE1204** [comment]
![2022-10-15_09h59_27](https://user-images.githubusercontent.com/82108974/195976198-8ce54dc1-d65f-4ba7-bc08-62a4b8ce3512.png)
Meaning the pink square which currently says +2 additional. This should show a scrollbar so that I can scroll through all events of that day.

**Comment by marksie1988** [comment]
That is not part of my calendar card, I think that is a screenshot of the default HA calendar
