### ISSUE TITLE
Option to show all calendar names for a duplicate event 

### ISSUE THREAD

**Issue by calvinbui** [totaldebug/atomic-calendar-revive#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an event is duplicated on multiple calendars, it only shows the name of one calendar it is duplicated on.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/3604363/193436986-aeb0a0a3-bf09-4677-ad4d-a4b7a5996e21.png">

### Expected behaviour

The event should have the option to show the name of all calendars it is on.

An example of what it might look like:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/3604363/193437040-24271f4d-aea9-4643-a988-f142524edde2.png">

### Context / Reason

This is helpful, so I know I am also invited/going to a particular event along with my wife.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rhgiter** [comment]
+1

**Comment by Digital-jedi12** [comment]
+1 :)
