### ISSUE TITLE
Events time not displaying as expected and inconsistenly

### ISSUE THREAD

**Issue by tykeal** [totaldebug/atomic-calendar-revive#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Events that span multiple days but are not all day events do not display their time in a consistent manner in events view.

For instance, Upcoming events show '<start time>, until <date> <end time>' as expected, but ongoing events just display 'Until <date>' and if it's the end day of the event it's '<start time> - <end time>' which doesn't make sense!

### Expected behaviour

Upcoming events are working as expected, ongoing events should do one of the following for the duration

For events that continue past the current day

My preferred:
Until <date> <time>

Current:
Until <date>

Mult-day events that end at a specific time _today_ should be listed as:
00:00 - <time>

Or
Until <time>

### Steps To Reproduce

Create events on a calendar that span multiple days with start and end times (that is, not marked as All-Day events)

### Card Version

v7.0.1

### Home Assistant Version

2022.10.0

### Configuration

```shell
type: custom:atomic-calendar-revive
name: 7925 Downstairs Calendar
enableModeChange: true
entities:
  - entity: calendar.rental_control_h4_7925_downstairs
    color: cyan
    icon: mdi:home-floor-a
    name: Rental Control H4 - 7925 (downstairs)
  - entity: calendar.rental_control_h4_7925_upstairs
    color: purple
    icon: mdi:home-floor-b
    name: Rental Control H4 - 7925 (upstairs)
  - entity: calendar.rental_control_h4_7925_r21
    color: magenta
    icon: mdi:home-floor-g
    name: Rental Control H4 - 7925 (R21)
firstDayOfWeek: 1
maxDaysToShow: 60
refreshInterval: 60
sortByStartTime: false
showCurrentEventLine: false
showMonth: true
showWeekDay: true
showFullDayProgress: true
showEventIcon: true
showNoEventsForToday: true
disableCalLink: true
disableCalEventLink: true
disableLocationLink: true
disableEventLink: true
showHiddenText: false
showDate: true
hideFinishedEvents: false
showRelativeTime: true
showLocation: true
dimFinishedEvents: true
showProgressBar: true
disableCalLocationLink: true
showWeekNumber: false
showCalendarName: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tykeal** [comment]
Example of what I'm seeing
![Screen Shot 2022-10-06 at 09 43 54](https://user-images.githubusercontent.com/1143598/194374825-23afd437-ddb5-4fe0-8a58-cd2b0bdbfa57.png)

**Comment by marksie1988** [comment]
Checked this and it is working in my latest build, hoping to get that released today.
