### ISSUE TITLE
Unable to change title or location text size

### ISSUE THREAD

**Issue by BadgerLoaf** [totaldebug/atomic-calendar-revive#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to change the size of the calendar entry text size, nor the location text size. However I have been able to successfully change the date and time text size, using the below parameters.  

I assume titleSize sets the size of the calendar entry name, and the locationTextSize the location text.

dateSize: 120
timeSize: 120
locationTextSize: 150
titleSize: 150
descSize: 150

### Expected behaviour

The text size of the entry name and the location should be larger.

### Steps To Reproduce

See attached configuration

### Card Version

7.0.1

### Home Assistant Version

2022.10.3

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.shared_birthdays
    name: Shared Birthdays
    icon: mdi:cake-variant
    color: orange
  - entity: calendar.shared_calendar
    name: Shared Calendar
maxDaysToShow: 1
showCurrentEventLine: false
showProgressBar: false
showMonth: false
showWeekDay: true
showDescription: false
disableEventLink: true
disableLocationLink: true
showNoEventsForToday: true
showFullDayProgress: false
showEventIcon: true
showHiddenText: false
showCalendarName: false
showWeekNumber: false
dimFinishedEvents: true
firstDayOfWeek: 1
refreshInterval: 60
hideDuplicates: true
showMultiDayEventParts: false
showLocation: true
showMultiDay: true
showDate: false
sortByStartTime: true
hoursFormat: HH:mm
showLoader: false
showRelativeTime: false
showHours: true
cardHeight: 300px
noEventText: We have an empty day.... nothing planned!
dateSize: 120
timeSize: 120
locationTextSize: 150
titleSize: 150
descSize: 150
card_mod:
  style: |
    ha-card {
      background-repeat: no-repeat;
      background-image: url("/local/images/calendar.png");
      background-size: 100% 100%;
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 5746787689** [comment]
Screenshot of above config

![Screenshot 2022-09-15 at 20 26 13](https://user-images.githubusercontent.com/108699847/196058087-5e48e0ed-0271-4694-b099-b2c273f81361.png)

**Comment by marksie1988** [comment]
Hi there,

I would recommend using cardmod for the modification of the styles, these size options were added by the original creator and if I added one for each style the card would be huge.

**Comment by 5746787689** [comment]
Thanks for the reply @marksie1988 

I was  hoping that those options could be fixed, but I understand things are not always as simple as they may appear. Appreciate all the work you do on this card, it really is great.

I'll see if I can work out the cardmod settings to change this seperately.

Thanks

**Comment by BadgerLoaf** [comment]
incase it's useful to anyone else, I have got this working using card-mod.

I removed these options:
`dateSize: 120
timeSize: 120
locationTextSize: 150
titleSize: 150
descSize: 150`


and included this code instead:
`card_mod:
  style: |
    .event-left {
      font-size: 20px !important;
    }
    .event-title {
      --event-title-size: 18px !important;
    }
    .event-titleRunning {
      --event-title-size: 18px !important;
    }
    .event-location {
      font-size: 16px !important;
    }
    .hoursHTML {
      --time-size: 14px !important;
    }`
