### ISSUE TITLE
refresh rate

### ISSUE THREAD

**Issue by bisix** [totaldebug/atomic-calendar-revive#861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if you put 5 min refresh the card every 5 seconds it refresh

### Expected behaviour

have a customrefresh rate of hassio calendar entity

### Context / Reason

avoit to refresh too fast

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
There is already a feature to set the card refresh rate, listed in the documentation.
