### ISSUE TITLE
showDate: true  does not compute correctly when startDaysAhead: is set

### ISSUE THREAD

**Issue by Some1Elsewhere** [totaldebug/atomic-calendar-revive#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When not defining a 'name = null' within the card but referring to 'showDate = True' to populate the header with the current date it will not recalculate while 'startDaysAhead =/ 0'. 

For Example ShowDate is True. Today is the 16. Dez. startDaysAhead is set to 2. showDate will not print 18th Dez but will stick to 16th.

### Expected behaviour

When ShowDate = True and StartDaysAhead is set to n . ShowDate needs to print Showdate + n to reflect the intendet date.

### Card Version

7.0.1

### Home Assistant Version

2022.12.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
`showDate` shows the current date, it is not designed to show a date in the future or past.

**Comment by Some1Elsewhere** [comment]
@marksie1988 fair enough, but why does showWeekDay then shows not the weekday of today as showDate does but the Date with startDaysAhead + Today?  

Isn't there the possibility to add this as a feature for ShowDate? ShowOffsetDate= True ?
It's already there with the weekdays, can't we have this for Date too?

**Comment by marksie1988** [comment]
I suppose this is possible yes. Could add it as a feature request. But worth noting I haven't had time to do any work on this for a while, hopefully I get some time next year to get all the current requests nailed.
