### ISSUE TITLE
Full day event hidden option

### ISSUE THREAD

**Issue by Fredzxda** [totaldebug/atomic-calendar-revive#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an event is a full day event, no ability to hide the information "Full day" for the event.

### Expected behaviour

No "Full day" shown in the card for full day event

### Possible Solutions

Option when set to true that modify the behavior of the card to not show "Full day"

### Context / Reason

Not relevant to show "Full day". Start time, end time only needed for event with hours

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
As there has been no update I will close this
