### ISSUE TITLE
Some screenshots?

### ISSUE THREAD

**Issue by cvladan** [totaldebug/atomic-calendar-revive#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please, can you give us some screenshots

### Expected behaviour

Some screenshots in documentation or README file

### Possible Solutions

Just take some screenshots and push to repo

### Context / Reason

I want to decide whether this add-in is worth installing and a screenshot is the fastest way to do that

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Basic screenshots added, however this doesnt show the full potential of the card due to the depth of customisation possible.
