### ISSUE TITLE
All day events show up as completed the day after

### ISSUE THREAD

**Issue by thriolsson** [totaldebug/atomic-calendar-revive#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When there was an all day event yesterday, the event shows up as a completed event today after in event mode.

### Expected behaviour

I do not expect to see the event from the previous day as a completed event for today.

### Steps To Reproduce

I am connected to a Google calendar.
Whenever I have an all day event yesterday, it shows up as a completed event today.
I have enabled to include all day enemy's and to show completed events as grayed out.
My time zone is GMT+1 in both HA and browser.

### Card Version

7.2.0

### Home Assistant Version

2033.1.1

### Configuration

```shell
type: custom:atomic-calendar-revive
enableModeChange: true
defaultMode: Event
firstDayOfWeek: 1
maxDaysToShow: 10
refreshInterval: 60
showNoEventDays: true
showWeekDay: true
entities:
  - entity: calendar.family
    color: orange
    name: Familjen
  - entity: calendar.6a_22_23_lax_och_provschema
    name: Läxor
    color: red
    icon: mdi:owl
  - entity: calendar.helgdagar_i_sverige
    name: Helgdagar
    color: green
    icon: mdi:party-popper
  - entity: calendar.hammarliden11_gmail_com
    name: Skolan
    icon: mdi:town-hall
dateFormat: L
hoursFormat: HH:mm
showRelativeTime: false
showDate: false
showLocation: false
disableCalLink: true
showMonth: false
disableEventLink: true
showNoEventsForToday: true
disableLocationLink: true
showEventIcon: true
showCalendarName: false
showEventDate: true
showDatePerEvent: false
showWeekNumber: false
showFullDayProgress: true
showCurrentEventLine: false
sortByStartTime: true
noEventText: Inga planer
untilText: fram till
showLoader: false
showProgressBar: false
fullDayEventText: hela dagen
showMultiDayEventParts: false
showMultiDay: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thriolsson** [comment]
![Screenshot_2023-01-08-09-25-32-73_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/16080236/211187070-7a639d31-bb3d-4fd4-93f9-0e3722e5123d.jpg)

The screenshot shows today's events. The event "Rebecka fyller år" was a full day event yesterday.

**Comment by thriolsson** [comment]
Today I had a full day event yesterday that does **not** show up as a completed event today. So it is not all cases, but there are some more conditions

**Comment by ajobbins** [comment]
I think this is the same issue as https://github.com/totaldebug/atomic-calendar-revive/issues/754

But it's still happening for me too on 7.2.0

**Comment by thriolsson** [comment]
It could be the same as #754, but please note that I did not see the event spill over to the next day until _after_ it completed.

/Thomas O
________________________________

**Comment by thriolsson** [comment]
Now it happened again. Is there anything I can do to troubleshoot this? Any additional info I can provide?

**Comment by bkr1969** [comment]
It doesn't look like anyone is looking at any issues currently.  Unfortunate.

**Comment by marksie1988** [comment]
> Now it happened again. Is there anything I can do to troubleshoot this? Any additional info I can provide?

This has been an issue for some time, it's to do with timezones, I just haven't had time to figure it out as in my timezone it works as expected. But I assume it's because Im GMT
