### ISSUE TITLE
In Denmark week 1 in a year is always the first week with at least 4 days in the new year.

### ISSUE THREAD

**Issue by TommyUnderbjergAndersen** [totaldebug/atomic-calendar-revive#911]
Week number is off.
In this screenshot it looks like week 4 is starting on Tuesday.
The week starting Monday the 16th of January is week 3, which is shown correct.

![image](https://user-images.githubusercontent.com/55131459/212744531-57b1ec71-f9f1-4644-8834-eb659682591b.png)

Configuration:

       - type: custom:atomic-calendar-revive
          name: Familie kalender
          enableModeChange: false
          maxEventCount: 14
          softLimit: 2
          showMonth: false
          showWeekDay: true
          showDate: true
          showMultiDay: true
          showMultiDayEventParts: true
          showWeekNumber: true
          entities:
            - entity: calendar.familie

**Comment by marksie1988** [comment]
Interesting, I tested this before the last release and it was showing correctly.  I will take another look, however this is calculated by the package dayjs so if it's an issue I would need to log it with them.

**Comment by TommyUnderbjergAndersen** [comment]
Why does it look like the week is changing on Tuesday. The other days are not showing week numbers:
![image](https://user-images.githubusercontent.com/55131459/212745233-88453d00-6069-4620-847c-affbc1802ec8.png)

**Comment by marksie1988** [comment]
Hmm yes that is strange! I have no idea why it would do that, I'll have to do some investigation.

**Comment by marksie1988** [comment]
this is same issue as #1070 closing
