### ISSUE TITLE
Card causes a lot of web requests

### ISSUE THREAD

**Issue by TheLastProject** [totaldebug/atomic-calendar-revive#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems the card can cause a lot of web requests. I'm not completely sure why this happens, but more info is available here: https://github.com/home-assistant/core/issues/85643

Basically, Home Assistant's documentation is misleading and only the most recent event is kept. So requesting any other event info from Home Assistant causes an additional web request.

I apologize for this issue having so little details, I'm quite short on time and energy lately but I figured a low-quality issue would still be more helpful than not reporting this. If there's something specific to test please tell me.

### Expected behaviour

Not sure but definitely less than 16 web requests per minute.

### Card Version

v7.2.0

### Home Assistant Version

2022.12.8

### Configuration

2 instances:

```
type: custom:atomic-calendar-revive
name: Events
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 14
refreshInterval: 600
showDate: true
showRelativeTime: true
showNoEventsForToday: true
entities:
  - calendar.contact_birthdays
  - calendar.sylvia_google
  - calendar.personal
  - calendar.tasks
  - calendar.holidays_in_netherlands
  - calendar.contacts
sortByStartTime: false
showMonth: false
showCurrentEventLine: false
showWeekDay: true
disableEventLink: false
disableLocationLink: false
showFullDayProgress: true
showEventIcon: false
showHiddenText: false
calShowDescription: false
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLink: false
showCalendarName: true
```

```
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 14
refreshInterval: 600
showDate: false
showRelativeTime: true
showNoEventsForToday: true
entities:
  - calendar.contact_birthdays
  - calendar.sylvia_google
  - calendar.personal
  - calendar.tasks
  - calendar.holidays_in_netherlands
  - calendar.contacts
sortByStartTime: false
showMonth: false
showCurrentEventLine: false
showWeekDay: true
disableEventLink: false
disableLocationLink: false
showFullDayProgress: true
showEventIcon: false
showHiddenText: false
calShowDescription: false
showLastCalendarWeek: true
disableCalEventLink: false
defaultMode: Calendar
disableCalLink: true
disableCalLocationLink: false
```

### Relevant log output

```shell
See other issue
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
There is nothing that can be done about this, as the other issue states, HA doesn't cache the events, this means we have to get the details each time the card refreshes, by default we refresh every 60 seconds hence why you see the requests every 60 seconds. 

You can set the `refreshInterval` option to a higher number to decrease how often it refreshes.

**Comment by marksie1988** [comment]
Closing as there is nothing that can be done about this other than changing the refresh interval.
