### ISSUE TITLE
No Description in CalDAV-Calendar

### ISSUE THREAD

**Issue by bernie78ger** [totaldebug/atomic-calendar-revive#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I sync to a nextcloud calendar (caldav/webdav) to integrate my exchange calendar in home assistant. 
Events show up, but the event description is not showing up in the dashboard card. The calendar entity has full description.
   
"calShowDescription" is set to true

### Expected behaviour

Description should be displayed as designed

### Card Version

7.2.0

### Home Assistant Version

2023.3.1

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.sr1
    name: SR1
    maxDaysToShow: 2
firstDayOfWeek: 1
maxDaysToShow: 2
refreshInterval: 120
showCurrentEventLine: false
showMonth: false
disableLocationLink: true
showFullDayProgress: false
showEventIcon: false
showCalendarName: true
showHiddenText: true
calShowDescription: true
disableCalLink: false
disableCalLocationLink: true
disableCalEventLink: true
showLastCalendarWeek: true
showDate: true
sortByStartTime: true
hideFinishedEvents: true
showRelativeTime: true
showLocation: false
showWeekDay: true
showNoEventsForToday: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Looking at your config you actually need `showDescription: true` if you are using event mode. 

`calShowDescription` is for calendar mode views
