### ISSUE TITLE
Option to not show all day/multi day events on agenda view

### ISSUE THREAD

**Issue by rubin110** [totaldebug/atomic-calendar-revive#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It would be great to have an option not to show any all day or multi day events on agenda view.

I'm using a spare phone on my desk that's display just this card, with the font sized big. Sadly the top half is completely covered by all day events that aren't as important as showing what the agenda is for the day.

### Expected behaviour

N/A

### Context / Reason

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RaphV90** [comment]
I would also be interested in having a solution for this, as I face the same issue.

I had a lookt at he source code of the webpage on the card itself and for me it looks like it's part of the 2nd `<div class="event-right">` of the event. As it's the same `div class` as the title of the event, I was not able to just change some values in the css file. 

How it improves spares display real estate can be seen in the following two screenshots:
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/77358711/aadc7378-4b24-44f2-9570-8cf128d994fe)
