### ISSUE TITLE
Ability to hide the event time from All Day events

### ISSUE THREAD

**Issue by Nuuki9** [totaldebug/atomic-calendar-revive#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an event is a full day event, no ability to hide the information "Full day" for the event.

### Expected behaviour

All Day events would onit the "All Day" or "All Day, until <date>" text that current appears beneath the event title.

### Possible Solutions

Option that when set modifies the behavior of the card to not show "Full day" for all day events.

### Context / Reason

Simplifies the information provided, and might allow for a more compact view, as the event would use only a single line of text.

This was previously requested (issue #876) but the requestor didn't follow up so it was closed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Could you please provide more information on what you mean here, currently an all day event does show "All Day" underneath. 

If you have a screenshot of what you think is wrong and needs changing that would help. 

Also is this in event mode or calendar mode?

**Comment by Nuuki9** [comment]
Apologies for being unclear - this is intended to be a new featue request, not an issue. As you say the current behaviour is that All Day events show "All Day", and the FR is to add a toggle to hide that.

**Comment by RaphV90** [comment]
I would also be interested in having a solution for this, as I face the same issue in event mode.

I had a lookt at he source code of the webpage on the card itself and for me it looks like it's part of the 2nd <div class="event-right"> of the event. As it's the same div class as the title of the event, I was not able to just change some values in the css file.

How it improves spares display real estate can be seen in the following two screenshots:

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/77358711/d5c75c36-4871-40db-bac3-bcb95923d09e)
