### ISSUE TITLE
0-minute events break the calendar

### ISSUE THREAD

**Issue by Firesphere** [totaldebug/atomic-calendar-revive#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calendars don't show in the frontend, throwing the following error:
```
Expected positive duration (29/04/2023 10:00 - 29/04/2023 10:00)
```

These are events that are more reminders for me, so they are (to me) expected to have 0 minutes

### Expected behaviour

The calendar shows

### Steps To Reproduce

Add a 0-minute event to a calendar

### Card Version

7.3.0

### Home Assistant Version

2023.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Could you confirm if you are using google calendar or caldav? 

I have tested with google calendar, and it shows it as a 30 min event, my caldav is broken atm so cant test with that yet.

**Comment by Firesphere** [comment]
It's a Baikal caldav calendar

**Comment by marksie1988** [comment]
I have been unable to test this, I use owncloud which doesnt allow a 0-minute event to be created. 

As such is not something I can test, and would argue that this isn't the intended use case for the card.
