### ISSUE TITLE
The calendar can't be loaded from Homeassistant component

### ISSUE THREAD

**Issue by PenthouseLA** [totaldebug/atomic-calendar-revive#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Google Calander working
2. ![image](https://user-images.githubusercontent.com/129676397/232214068-261f6273-3d2a-41ac-b07f-a80b5cd1ff87.png)

### Expected behaviour

1. Google Calander working
2. Google Calender delete + reauth with new Codes

error dont be remove:
![image](https://user-images.githubusercontent.com/129676397/232214068-261f6273-3d2a-41ac-b07f-a80b5cd1ff87.png)

### Card Version

v7.3.0

### Home Assistant Version

2023.4.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acht11** [comment]
Hello all, I have the same problem with a nextcloud calendar.
My HA Version:
![image](https://user-images.githubusercontent.com/86398696/232218763-c50a26e5-4f4b-4195-adac-5c59bad6a247.png)

My Calendar:
![image](https://user-images.githubusercontent.com/86398696/232220275-f81cf69e-71b5-4131-a1cf-c7da57307286.png)
![image](https://user-images.githubusercontent.com/86398696/232220437-779c1608-17f6-48e3-82b7-cf1eb5a20b6f.png)

change the entitie manualy, than it works.
![image](https://user-images.githubusercontent.com/86398696/232220741-dff394ff-5860-4f21-903a-fdcb26e54035.png)

So, I would say, there is a problem with the visual configuration.
![image](https://user-images.githubusercontent.com/86398696/232221151-49b967ba-1b10-4999-9740-cc96eee2348a.png)

**Comment by marksie1988** [comment]
> Hello all, I have the same problem with a nextcloud calendar. My HA Version: ![image](https://user-images.githubusercontent.com/86398696/232218763-c50a26e5-4f4b-4195-adac-5c59bad6a247.png)
> 
> My Calendar: ![image](https://user-images.githubusercontent.com/86398696/232220275-f81cf69e-71b5-4131-a1cf-c7da57307286.png) ![image](https://user-images.githubusercontent.com/86398696/232220437-779c1608-17f6-48e3-82b7-cf1eb5a20b6f.png)
> 
> change the entitie manualy, than it works. ![image](https://user-images.githubusercontent.com/86398696/232220741-dff394ff-5860-4f21-903a-fdcb26e54035.png)
> 
> So, I would say, there is a problem with the visual configuration. ![image](https://user-images.githubusercontent.com/86398696/232221151-49b967ba-1b10-4999-9740-cc96eee2348a.png)

Yes that does look like issues with the editor, I probably need to rework it since they moved to different icons I never updated it all.

**Comment by marksie1988** [comment]
Tracking in #1021
